//! Baro-driven storm detection — the roadmap's "Weather / storm alerts" row,
//! and [`vision.md`](../../../../docs/custom_watch/vision.md) req #7's second
//! job for the barometer.
//!
//! # The problem this module is entirely about
//!
//! A falling barometer means weather. It also means climbing, and on a mountain
//! ultra the second signal dwarfs the first by two orders of magnitude: an
//! approaching front moves station pressure a few hectopascals over hours,
//! while 500 m of ascent moves it ~57 hPa in forty minutes. Trending raw
//! station pressure on this device would therefore announce a storm on every
//! col and clear it on every descent — a warning generated by the runner's own
//! legs.
//!
//! The separation is a **pressure reduction**: compensate each reading to the
//! sea-level-equivalent pressure it implies at the altitude it was taken at
//! ([`crate::elevation::sea_level_pa`], the exact inverse of the altitude
//! conversion), and trend *that*. Climbing moves the station pressure and the
//! altitude together, so the reduced value does not move; a front moves the
//! station pressure alone, so it does.
//!
//! # The altitude has to be independent, and that decides everything else
//!
//! The reduction is only a measurement if its altitude came from somewhere
//! other than the barometer. Feed back a baro-derived altitude and the
//! reduction returns the reference it was derived against — exactly, on every
//! sample, with the weather divided back out (pinned by
//! `a_baro_derived_altitude_reduces_back_to_the_reference_it_came_from` in
//! [`crate::elevation`]). So the reference is the **GPS receiver's** altitude,
//! narrowed through the same [`crate::elevation::plausible_gps`] window the
//! vert filter refuses to pull its bias toward, and nothing else.
//!
//! **Not the complementary filter's corrected altitude**, which is the
//! tempting reuse and is wrong here. That altitude is `HPF(baro) + LPF(gps)`:
//! high-frequency barometer, low-frequency GPS, crossing over at
//! `elevation::GPS_PULL` per *fix*. Reduce against it and the error term is
//! `HPF(weather)` — the very signal being measured, suppressed by exactly the
//! filter that makes the altitude smooth. In Expedition mode, where a fix
//! lands once a minute, that crossover sits around a hundred minutes and would
//! swallow most of a three-hour trend. The filter is right for vert (its job is
//! to remove weather) and wrong for weather (whose job is to keep it).
//!
//! Trading smoothness away costs noise instead, and noise is what the rest of
//! this module is: a receiver altitude carries ~±15 m, which is ~1.8 hPa of
//! reduction error — comparable to the storm signal itself. Two averages
//! answer it. Samples are averaged into [`StormTracker::bucket_s`] buckets,
//! each requiring [`STORM_BUCKET_MIN_SAMPLES`] corroborated readings before it
//! banks at all, and the trend is a least-squares slope over every banked
//! bucket in the window rather than a difference of its two endpoints. An
//! endpoint difference stakes the whole verdict on two samples; one bad
//! altitude at either end moves it by more than the threshold.
//!
//! # What it refuses to say
//!
//! No corroborated GPS altitude within [`STORM_REFERENCE_MAX_AGE_S`] and the
//! answer is [`StormTrend::NoReference`] — not a trend computed off the last
//! good reference, and emphatically not a trend read off raw station pressure.
//! Under canopy, in a canyon, or with the receiver napping, the watch cannot
//! tell a front from a climb, and the honest report of that is that it does not
//! know. Less than a third of the window banked and the answer is
//! [`StormTrend::Building`]: a tendency extrapolated from a fraction of its
//! window amplifies its own noise by the reciprocal of that fraction, and a
//! fabricated warning is worse than no warning at all.
//!
//! # Thresholds
//!
//! The window is three hours because that is the synoptic pressure-tendency
//! interval every barometric convention is quoted over. [`STORM_FALL_HPA`] =
//! 4.0 is the fall the mainstream outdoor-watch storm alarms ship as their
//! default. Both are **chosen, not measured** — nothing in this repository has
//! watched a real front cross a real barometer — and they are registered as
//! such in `quality_standards.md`. [`STORM_CLEAR_FRACTION`] releases the latch at
//! half the opening fall, the same open-wide / close-narrow asymmetry
//! [`crate::climb`] uses, so a trend hovering on the boundary cannot flap the
//! word on the page.
//!
//! Pure logic, no peripherals, no allocator, like the rest of `core`. There is
//! no web helper to port: storm detection is a barometer feature and the phone
//! has no barometer in this product.

use crate::elevation::{plausible_gps, sea_level_pa};

/// Seconds of samples averaged into one banked point.
///
/// Five minutes: long enough that a bucket averages down the receiver's
/// altitude noise even at the slowest fix cadence the watch offers, short
/// enough that [`STORM_HISTORY`] covers the whole window in fixed RAM.
pub const STORM_BUCKET_S: u32 = 300;

/// The trend window — three hours, the synoptic pressure-tendency interval.
pub const STORM_WINDOW_S: u32 = 10_800;

/// Banked points the ring holds: one window's worth, plus the boundary point.
pub const STORM_HISTORY: usize = (STORM_WINDOW_S / STORM_BUCKET_S) as usize + 1;

/// Corroborated readings a bucket needs before it banks.
///
/// A single receiver altitude carries ~±15 m, which is ~1.8 hPa of reduction
/// error — a third of the opening threshold, off one sample. Three brings it to
/// ~1 hPa before the regression across the window takes it the rest of the way;
/// below three there is no averaging at all and one bad fix would move a banked
/// point by more than the storm signal.
pub const STORM_BUCKET_MIN_SAMPLES: u16 = 3;

/// How old the last corroborated GPS altitude may be before the trend goes to
/// [`StormTrend::NoReference`].
///
/// Two minutes, and deliberately **not** scaled with
/// [`StormTracker::bucket_s`]: this is a claim about the receiver, not about
/// the trend window. Expedition mode publishes a fix once every 60 s
/// ([`crate::gnss_mode`]), so twice that is the smallest budget a healthy watch
/// always passes in every mode.
pub const STORM_REFERENCE_MAX_AGE_S: u32 = 120;

/// Fall over the window that opens a storm — the value the mainstream outdoor
/// watches ship as their storm-alarm default. Chosen, not measured.
pub const STORM_FALL_HPA: f32 = 4.0;

/// Fall the trend must recover *above* before a latched storm releases. Half
/// the opening fall, the same asymmetry [`crate::climb`]'s 20 m / 10 m pair
/// uses and for the same reason: a boundary the trend hovers on must not flap
/// the word the runner is reading.
pub const STORM_CLEAR_FRACTION: f32 = 0.5;

/// Movement over the window smaller than this reads as [`StormTrend::Steady`].
/// The residual the reduction cannot resolve after both averages, rounded up —
/// below it the sign of the slope is not a claim worth making.
pub const STORM_STEADY_BAND_HPA: f32 = 1.0;

/// Plausibility window for a pushed opening threshold. The floor is the steady
/// band (a threshold inside the noise would fire on nothing); the ceiling is
/// past any tendency a terrestrial barometer records over three hours, so a
/// value beyond it could never fire.
pub const STORM_THRESHOLD_MIN_HPA: f32 = STORM_STEADY_BAND_HPA;
pub const STORM_THRESHOLD_MAX_HPA: f32 = 20.0;

/// What the barometer can say about the weather right now.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum StormTrend {
    /// No GPS altitude has corroborated the barometer recently, so a reduction
    /// would be circular and a climb indistinguishable from a front. The watch
    /// does not know, and says so.
    NoReference,
    /// Corroborated, but less than a third of the window is banked — too little
    /// to extrapolate a tendency from without amplifying its own noise.
    Building,
    /// Falling past [`StormTracker::fall_threshold_hpa`], latched until the
    /// trend recovers above [`STORM_CLEAR_FRACTION`] of it.
    Storm,
    Falling,
    Steady,
    Rising,
}

impl StormTrend {
    /// Whether the trend is a measurement rather than a refusal — the page's
    /// data-presence bit.
    pub const fn is_measured(self) -> bool {
        matches!(
            self,
            Self::Storm | Self::Falling | Self::Steady | Self::Rising
        )
    }
}

/// What the Storm page shows and the alert arm reads.
#[derive(Clone, Copy, Debug, PartialEq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct StormView {
    pub trend: StormTrend,
    /// The sea-level-equivalent pressure of the most recent corroborated
    /// reading, hPa. Present whenever a reference is live — including through
    /// [`StormTrend::Building`], because the absolute pressure is known from
    /// the first reading even though its tendency is not.
    pub sea_level_hpa: Option<f32>,
    /// Change over one whole window, from the fitted slope. Negative is
    /// falling. `None` unless the trend is measured.
    pub delta_hpa: Option<f32>,
    /// Seconds actually spanned by the banked points the slope was fitted to —
    /// never more than the window, and less while the history is still filling
    /// or a signal void has thinned it.
    pub span_s: u32,
}

#[derive(Clone, Copy, Debug, PartialEq)]
struct Banked {
    at_s: u32,
    hpa: f32,
}

/// Streaming reducer + trend fitter, fed one barometer reading per sample tick
/// alongside whatever GPS altitude arrived with it.
///
/// The instrument outlives a run: the weather does not restart when the runner
/// presses start, and a three-hour window banked while walking to the trailhead
/// is exactly the history that makes the first hour of the race honest. There
/// is deliberately no `reset`.
pub struct StormTracker {
    bucket_s: u32,
    window_s: u32,
    /// Least span the slope may be fitted over: a third of the window, so the
    /// extrapolation to a whole window never multiplies the residual by more
    /// than three.
    min_span_s: u32,
    fall_threshold_hpa: f32,
    ring: [Banked; STORM_HISTORY],
    len: usize,
    next: usize,
    /// The bucket still filling: its first and last sample times, the running
    /// sum, and how many readings landed in it.
    open_from_s: u32,
    open_to_s: u32,
    open_sum_hpa: f64,
    open_n: u16,
    open: bool,
    /// The most recent corroborated reading, whatever bucket it fell in — the
    /// freshness gate and the displayed absolute pressure both read it.
    last_hpa: f32,
    last_at_s: Option<u32>,
    latched: bool,
}

impl Default for StormTracker {
    fn default() -> Self {
        Self::new()
    }
}

impl StormTracker {
    pub const fn new() -> Self {
        Self::with_cadence(STORM_BUCKET_S, STORM_WINDOW_S)
    }

    /// A tracker on a shortened cadence — the sim's, which cannot spend three
    /// hours of virtual time watching a front. `window_s` is clamped to at
    /// least two buckets (a slope needs two points) and to what
    /// [`STORM_HISTORY`] can hold, so no caller can ask for a window the ring
    /// silently truncates.
    pub const fn with_cadence(bucket_s: u32, window_s: u32) -> Self {
        let bucket_s = if bucket_s == 0 { 1 } else { bucket_s };
        let widest = bucket_s * (STORM_HISTORY as u32 - 1);
        let window_s = if window_s < bucket_s * 2 {
            bucket_s * 2
        } else if window_s > widest {
            widest
        } else {
            window_s
        };
        Self {
            bucket_s,
            window_s,
            min_span_s: window_s / 3,
            fall_threshold_hpa: STORM_FALL_HPA,
            ring: [Banked { at_s: 0, hpa: 0.0 }; STORM_HISTORY],
            len: 0,
            next: 0,
            open_from_s: 0,
            open_to_s: 0,
            open_sum_hpa: 0.0,
            open_n: 0,
            open: false,
            last_hpa: 0.0,
            last_at_s: None,
            latched: false,
        }
    }

    /// The fall over one window that opens a storm. An implausible value leaves
    /// the current threshold standing rather than clamping to an edge — a
    /// clamped threshold is a confidently wrong alarm, the same rule the QNH
    /// and timezone pushes follow.
    pub fn set_fall_threshold_hpa(&mut self, hpa: f32) {
        if hpa.is_finite() && (STORM_THRESHOLD_MIN_HPA..=STORM_THRESHOLD_MAX_HPA).contains(&hpa) {
            self.fall_threshold_hpa = hpa;
        }
    }

    pub fn fall_threshold_hpa(&self) -> f32 {
        self.fall_threshold_hpa
    }

    /// Feed one barometer reading with the GPS altitude that arrived alongside
    /// it, if any.
    ///
    /// `gps_alt_m` is the whole freshness contract: a sample with no
    /// corroborating altitude contributes **nothing**, so the window can only
    /// ever hold reductions that had an independent reference at the moment
    /// they were taken. There is no separate staleness bookkeeping on the way
    /// in — a signal void simply stops banking, and [`Self::view`] notices the
    /// silence.
    pub fn on_sample(&mut self, pressure_pa: f32, gps_alt_m: Option<f32>, now_s: u32) {
        let Some(alt_m) = plausible_gps(gps_alt_m) else {
            return;
        };
        let Some(pa) = sea_level_pa(pressure_pa, alt_m) else {
            return;
        };
        let hpa = pa / 100.0;
        self.last_hpa = hpa;
        self.last_at_s = Some(now_s);

        // A sample outside the open bucket's span closes it. `now_s <
        // open_from_s` catches a clock that went backwards (nothing on this
        // device does, but a bucket accumulating against a negative age would
        // never close).
        let outside = !self.open
            || now_s < self.open_from_s
            || now_s.saturating_sub(self.open_from_s) >= self.bucket_s;
        if outside {
            self.close_open();
            self.open = true;
            self.open_from_s = now_s;
            self.open_sum_hpa = 0.0;
            self.open_n = 0;
        }
        self.open_to_s = now_s;
        self.open_sum_hpa += f64::from(hpa);
        self.open_n = self.open_n.saturating_add(1);
    }

    /// The trend as of `now_s`.
    pub fn view(&self, now_s: u32) -> StormView {
        let reference_live = self
            .last_at_s
            .is_some_and(|at| now_s.saturating_sub(at) <= STORM_REFERENCE_MAX_AGE_S);
        if !reference_live {
            return StormView {
                trend: StormTrend::NoReference,
                sea_level_hpa: None,
                delta_hpa: None,
                span_s: 0,
            };
        }
        let building = StormView {
            trend: StormTrend::Building,
            sea_level_hpa: Some(self.last_hpa),
            delta_hpa: None,
            span_s: 0,
        };

        let mut oldest = u32::MAX;
        let mut newest = 0u32;
        let mut n = 0u32;
        for b in self.in_window(now_s) {
            oldest = oldest.min(b.at_s);
            newest = newest.max(b.at_s);
            n += 1;
        }
        if n < 2 {
            return building;
        }
        let span_s = newest - oldest;
        if span_s < self.min_span_s {
            return building;
        }
        let Some(slope_hpa_per_s) = self.slope(now_s, oldest) else {
            return building;
        };
        let delta_hpa = (slope_hpa_per_s * f64::from(self.window_s)) as f32;
        StormView {
            trend: self.classify(delta_hpa),
            sea_level_hpa: Some(self.last_hpa),
            delta_hpa: Some(delta_hpa),
            span_s,
        }
    }

    /// Fold the trend's own latch forward. Separated from [`Self::view`], which
    /// is a pure read a renderer may call as often as it likes, because a latch
    /// that advanced on every read would depend on how often the page was
    /// drawn.
    pub fn on_view(&mut self, view: &StormView) {
        let Some(delta) = view.delta_hpa else {
            // No measurement is not a recovery: a signal void must not clear a
            // storm the watch was already reporting, or a runner stepping into
            // a canyon would see the warning vanish with the weather unchanged.
            return;
        };
        if delta <= -self.fall_threshold_hpa {
            self.latched = true;
        } else if delta > -self.fall_threshold_hpa * STORM_CLEAR_FRACTION {
            self.latched = false;
        }
    }

    fn classify(&self, delta_hpa: f32) -> StormTrend {
        let opening = delta_hpa <= -self.fall_threshold_hpa;
        let holding = self.latched && delta_hpa <= -self.fall_threshold_hpa * STORM_CLEAR_FRACTION;
        if opening || holding {
            StormTrend::Storm
        } else if delta_hpa <= -STORM_STEADY_BAND_HPA {
            StormTrend::Falling
        } else if delta_hpa >= STORM_STEADY_BAND_HPA {
            StormTrend::Rising
        } else {
            StormTrend::Steady
        }
    }

    fn in_window(&self, now_s: u32) -> impl Iterator<Item = &Banked> {
        let window_s = self.window_s;
        self.ring[..self.len]
            .iter()
            .filter(move |b| now_s.saturating_sub(b.at_s) <= window_s)
    }

    /// Least-squares slope in hPa per second over the banked points in the
    /// window, with time re-based on `origin_s` so the normal equations stay
    /// inside `f64`'s exact-integer range whatever the uptime.
    fn slope(&self, now_s: u32, origin_s: u32) -> Option<f64> {
        let (mut n, mut st, mut sp, mut stt, mut stp) = (0.0f64, 0.0f64, 0.0f64, 0.0f64, 0.0f64);
        for b in self.in_window(now_s) {
            let t = f64::from(b.at_s.saturating_sub(origin_s));
            let p = f64::from(b.hpa);
            n += 1.0;
            st += t;
            sp += p;
            stt += t * t;
            stp += t * p;
        }
        let denominator = n * stt - st * st;
        if denominator <= 0.0 {
            return None;
        }
        let slope = (n * stp - st * sp) / denominator;
        slope.is_finite().then_some(slope)
    }

    /// Bank the open bucket if enough readings landed in it, then forget it.
    /// A bucket short of [`STORM_BUCKET_MIN_SAMPLES`] is dropped rather than
    /// banked thin — one un-averaged reduction carries more error than the
    /// signal.
    fn close_open(&mut self) {
        if !self.open {
            return;
        }
        self.open = false;
        if self.open_n < STORM_BUCKET_MIN_SAMPLES {
            return;
        }
        let banked = Banked {
            // The midpoint of the readings that made it, not of the bucket:
            // a bucket whose samples all landed in its first seconds is a
            // measurement of those seconds.
            at_s: self.open_from_s + (self.open_to_s - self.open_from_s) / 2,
            hpa: (self.open_sum_hpa / f64::from(self.open_n)) as f32,
        };
        self.ring[self.next] = banked;
        self.next = (self.next + 1) % STORM_HISTORY;
        self.len = (self.len + 1).min(STORM_HISTORY);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::elevation::altitude_m;

    /// Station pressure at `alt_m` under a sea-level reference of `p0_hpa` —
    /// the atmosphere a test scripts, inverted the way the sim's BMP581 model
    /// inverts it.
    fn station_pa(alt_m: f32, p0_hpa: f32) -> f32 {
        let p0 = p0_hpa * 100.0;
        // Solve altitude_m(p, p0) == alt_m for p by bisection: the module under
        // test owns the closed form, so a test that reused it would be checking
        // the formula against itself.
        let (mut lo, mut hi) = (1.0f32, p0);
        for _ in 0..80 {
            let mid = 0.5 * (lo + hi);
            if altitude_m(mid, p0) > alt_m {
                lo = mid;
            } else {
                hi = mid;
            }
        }
        0.5 * (lo + hi)
    }

    /// Walk a tracker at 1 Hz for `secs` seconds from `from_s`, with the
    /// altitude and sea-level reference each a function of the second.
    fn walk(
        t: &mut StormTracker,
        from_s: u32,
        secs: u32,
        alt: impl Fn(u32) -> f32,
        p0_hpa: impl Fn(u32) -> f32,
    ) -> u32 {
        for i in 0..secs {
            let now = from_s + i;
            let a = alt(i);
            t.on_sample(station_pa(a, p0_hpa(i)), Some(a), now);
        }
        from_s + secs
    }

    /// A tracker on a cadence a test can walk in a few thousand ticks: 60 s
    /// buckets over a 30-minute window. The arithmetic under test is
    /// cadence-independent — only the constants change.
    fn fast() -> StormTracker {
        StormTracker::with_cadence(60, 1_800)
    }

    #[test]
    fn a_flat_atmosphere_reads_steady() {
        let mut t = fast();
        let end = walk(&mut t, 0, 2_000, |_| 1_600.0, |_| 1_013.0);
        let v = t.view(end);
        assert_eq!(v.trend, StormTrend::Steady, "{v:?}");
        assert!(v.delta_hpa.unwrap().abs() < 0.1, "{v:?}");
        assert!((v.sea_level_hpa.unwrap() - 1_013.0).abs() < 1.0, "{v:?}");
    }

    #[test]
    fn a_climb_at_constant_weather_is_not_a_storm() {
        // The whole reason this module exists. 700 m of ascent drops station
        // pressure by ~80 hPa — twenty times the storm threshold — and the
        // reduced pressure must not move.
        let mut t = fast();
        let end = walk(
            &mut t,
            0,
            2_000,
            |i| 1_600.0 + f64::from(i) as f32 * 0.35,
            |_| 1_013.0,
        );
        let v = t.view(end);
        assert_eq!(
            v.trend,
            StormTrend::Steady,
            "a climb read as weather: {v:?}"
        );
        assert!(v.delta_hpa.unwrap().abs() < 1.0, "{v:?}");
    }

    #[test]
    fn a_descent_at_constant_weather_is_not_a_clearing_sky() {
        let mut t = fast();
        let end = walk(
            &mut t,
            0,
            2_000,
            |i| 2_400.0 - f64::from(i) as f32 * 0.35,
            |_| 1_013.0,
        );
        assert_eq!(t.view(end).trend, StormTrend::Steady);
    }

    #[test]
    fn a_falling_front_on_flat_ground_reads_a_storm() {
        // -6 hPa over the 1800 s window, applied at a steady rate.
        let mut t = fast();
        let end = walk(
            &mut t,
            0,
            2_400,
            |_| 300.0,
            |i| 1_013.0 - 6.0 * f64::from(i) as f32 / 1_800.0,
        );
        let v = t.view(end);
        assert_eq!(v.trend, StormTrend::Storm, "{v:?}");
        let delta = v.delta_hpa.unwrap();
        assert!((delta + 6.0).abs() < 0.3, "delta {delta}");
        assert!(v.span_s > t.min_span_s);
    }

    #[test]
    fn a_falling_front_while_climbing_still_reads_the_front() {
        // The composed case, and the one a station-pressure trend gets right
        // only by accident: the runner climbs 700 m while the front takes 6 hPa
        // out of the atmosphere. The reduction must report the 6, not the 86.
        let mut t = fast();
        let end = walk(
            &mut t,
            0,
            2_400,
            |i| 1_600.0 + f64::from(i) as f32 * 0.35,
            |i| 1_013.0 - 6.0 * f64::from(i) as f32 / 1_800.0,
        );
        let v = t.view(end);
        assert_eq!(v.trend, StormTrend::Storm, "{v:?}");
        assert!((v.delta_hpa.unwrap() + 6.0).abs() < 0.5, "{v:?}");
    }

    #[test]
    fn a_rising_barometer_reads_rising_and_never_alarms() {
        let mut t = fast();
        let end = walk(
            &mut t,
            0,
            2_400,
            |_| 300.0,
            |i| 1_005.0 + 6.0 * f64::from(i) as f32 / 1_800.0,
        );
        let v = t.view(end);
        assert_eq!(v.trend, StormTrend::Rising, "{v:?}");
        assert!(v.delta_hpa.unwrap() > 0.0);
    }

    #[test]
    fn a_shallow_fall_is_falling_but_not_a_storm() {
        let mut t = fast();
        let end = walk(
            &mut t,
            0,
            2_400,
            |_| 300.0,
            |i| 1_013.0 - 2.0 * f64::from(i) as f32 / 1_800.0,
        );
        assert_eq!(t.view(end).trend, StormTrend::Falling);
    }

    #[test]
    fn no_gps_altitude_is_no_reference_not_a_station_pressure_trend() {
        // Station pressure collapses by 40 hPa while the runner climbs with no
        // fix. Nothing may be banked, and nothing may be claimed.
        let mut t = fast();
        for i in 0..2_400u32 {
            t.on_sample(station_pa(300.0 + i as f32 * 0.15, 1_013.0), None, i);
        }
        let v = t.view(2_400);
        assert_eq!(v.trend, StormTrend::NoReference);
        assert_eq!(v.delta_hpa, None);
        assert_eq!(v.sea_level_hpa, None);
    }

    #[test]
    fn an_implausible_gps_altitude_corroborates_nothing() {
        let mut t = fast();
        for i in 0..2_400u32 {
            let bad = if i % 2 == 0 {
                Some(f32::NAN)
            } else {
                Some(1.0e9)
            };
            t.on_sample(station_pa(300.0, 1_013.0), bad, i);
        }
        assert_eq!(t.view(2_400).trend, StormTrend::NoReference);
    }

    #[test]
    fn a_reference_that_goes_stale_withdraws_the_trend() {
        // A canyon, a canopy, a receiver in backup mode: the trend was real and
        // then the corroboration stopped. The watch reports that it stopped.
        let mut t = fast();
        let end = walk(
            &mut t,
            0,
            2_400,
            |_| 300.0,
            |i| 1_013.0 - 6.0 * f64::from(i) as f32 / 1_800.0,
        );
        assert_eq!(t.view(end).trend, StormTrend::Storm);
        // `walk` leaves the clock one tick past its last sample, so the budget
        // is measured from there.
        let last = end - 1;
        assert_eq!(
            t.view(last + STORM_REFERENCE_MAX_AGE_S).trend,
            StormTrend::Storm,
            "inside the budget the trend still stands"
        );
        assert_eq!(
            t.view(last + STORM_REFERENCE_MAX_AGE_S + 1).trend,
            StormTrend::NoReference
        );
    }

    #[test]
    fn a_short_history_is_building_not_a_verdict() {
        // A tendency extrapolated from a fifth of its window multiplies its own
        // residual fivefold; the honest answer is that it is not ready.
        let mut t = fast();
        let end = walk(
            &mut t,
            0,
            300,
            |_| 300.0,
            |i| 1_013.0 - 6.0 * f64::from(i) as f32 / 1_800.0,
        );
        let v = t.view(end);
        assert_eq!(v.trend, StormTrend::Building);
        assert_eq!(v.delta_hpa, None);
        // The absolute pressure IS known from the first reading, and the page
        // shows it — only its tendency is withheld.
        assert!(v.sea_level_hpa.is_some());
    }

    #[test]
    fn the_minimum_span_is_a_third_of_the_window() {
        let t = fast();
        assert_eq!(t.min_span_s, t.window_s / 3);
        assert_eq!(StormTracker::new().min_span_s, STORM_WINDOW_S / 3);
    }

    #[test]
    fn a_thin_bucket_is_dropped_rather_than_banked() {
        // One reduction is ~1.8 hPa of altitude noise on its own. A bucket that
        // caught fewer than three readings must not become a point the slope is
        // fitted through.
        let mut t = StormTracker::with_cadence(10, 120);
        // Two readings per 10 s bucket, for two minutes.
        for i in 0..12u32 {
            for k in 0..2u32 {
                let at = i * 10 + k;
                t.on_sample(station_pa(300.0, 1_013.0), Some(300.0), at);
            }
        }
        assert_eq!(t.len, 0, "thin buckets banked");
        assert_eq!(t.view(120).trend, StormTrend::Building);
    }

    #[test]
    fn the_storm_latch_holds_through_a_partial_recovery() {
        // Open at the threshold, then let the fall shallow to just inside it:
        // the word must not flicker off and on while the front is still there.
        let mut t = fast();
        let mut v = StormView {
            trend: StormTrend::Steady,
            sea_level_hpa: None,
            delta_hpa: Some(-4.5),
            span_s: 600,
        };
        t.on_view(&v);
        assert_eq!(t.classify(-4.5), StormTrend::Storm);
        // Recovered past the opening threshold but not past the release: held.
        v.delta_hpa = Some(-3.0);
        t.on_view(&v);
        assert_eq!(t.classify(-3.0), StormTrend::Storm);
        // Past the release: cleared, and it stays cleared at the same value.
        v.delta_hpa = Some(-1.9);
        t.on_view(&v);
        assert_eq!(t.classify(-1.9), StormTrend::Falling);
        assert_eq!(t.classify(-3.0), StormTrend::Falling);
    }

    #[test]
    fn a_lost_reference_does_not_clear_a_latched_storm() {
        // The front is still out there; the watch merely stopped being able to
        // see it. Clearing on silence would retract a warning on no evidence.
        let mut t = fast();
        t.on_view(&StormView {
            trend: StormTrend::Storm,
            sea_level_hpa: None,
            delta_hpa: Some(-5.0),
            span_s: 900,
        });
        assert!(t.latched);
        t.on_view(&StormView {
            trend: StormTrend::NoReference,
            sea_level_hpa: None,
            delta_hpa: None,
            span_s: 0,
        });
        assert!(t.latched, "silence cleared the latch");
    }

    #[test]
    fn the_threshold_setter_refuses_what_it_cannot_believe() {
        let mut t = fast();
        for bad in [
            0.0,
            STORM_THRESHOLD_MIN_HPA - 0.01,
            STORM_THRESHOLD_MAX_HPA + 0.01,
            -4.0,
            f32::NAN,
            f32::INFINITY,
        ] {
            t.set_fall_threshold_hpa(bad);
            assert_eq!(t.fall_threshold_hpa(), STORM_FALL_HPA, "{bad} was taken");
        }
        t.set_fall_threshold_hpa(2.0);
        assert_eq!(t.fall_threshold_hpa(), 2.0);
        // ...and the release scales with it.
        assert_eq!(t.classify(-1.5), StormTrend::Falling);
        t.on_view(&StormView {
            trend: StormTrend::Steady,
            sea_level_hpa: None,
            delta_hpa: Some(-2.0),
            span_s: 900,
        });
        assert_eq!(t.classify(-1.5), StormTrend::Storm);
    }

    #[test]
    fn the_window_can_never_outrun_the_ring() {
        // A caller asking for more window than STORM_HISTORY holds would get a
        // trend fitted over a silently truncated history.
        let t = StormTracker::with_cadence(300, 1_000_000);
        assert_eq!(t.window_s, 300 * (STORM_HISTORY as u32 - 1));
        assert_eq!(t.window_s, STORM_WINDOW_S);
        // ...and a window under two buckets cannot hold the two points a slope
        // needs.
        let t = StormTracker::with_cadence(300, 10);
        assert_eq!(t.window_s, 600);
    }

    #[test]
    fn the_default_ring_holds_exactly_one_window() {
        assert_eq!(STORM_HISTORY, 37);
        let t = StormTracker::new();
        assert_eq!(t.window_s, STORM_WINDOW_S);
        assert_eq!(t.bucket_s, STORM_BUCKET_S);
    }

    #[test]
    fn points_older_than_the_window_leave_the_trend() {
        // A steep fall, then flat air for a whole window: the fall must age out
        // rather than keeping a storm on the page for the rest of the day.
        let mut t = fast();
        let end = walk(
            &mut t,
            0,
            2_400,
            |_| 300.0,
            |i| 1_013.0 - 6.0 * f64::from(i) as f32 / 1_800.0,
        );
        assert_eq!(t.view(end).trend, StormTrend::Storm);
        let end = walk(&mut t, end, 2_400, |_| 300.0, |_| 1_005.0);
        let v = t.view(end);
        assert!(
            v.delta_hpa.unwrap().abs() < 0.5,
            "the aged-out fall still moves the slope: {v:?}"
        );
    }

    #[test]
    fn a_signal_void_mid_window_keeps_the_trend_it_can_still_measure() {
        // Both ends of the window were corroborated; only the middle was lost.
        // The slope over what remains is a real measurement of a real interval,
        // so the void costs resolution, not the verdict.
        let mut t = fast();
        let end = walk(
            &mut t,
            0,
            600,
            |_| 300.0,
            |i| 1_013.0 - 6.0 * f64::from(i) as f32 / 1_800.0,
        );
        for i in 0..600u32 {
            t.on_sample(station_pa(300.0, 1_011.0), None, end + i);
        }
        let end = walk(
            &mut t,
            end + 600,
            600,
            |_| 300.0,
            |i| 1_009.0 - 6.0 * f64::from(i) as f32 / 1_800.0,
        );
        let v = t.view(end);
        assert_eq!(v.trend, StormTrend::Storm, "{v:?}");
        assert!(v.span_s >= t.min_span_s);
    }

    #[test]
    fn a_measured_trend_is_the_pages_presence_bit() {
        assert!(!StormTrend::NoReference.is_measured());
        assert!(!StormTrend::Building.is_measured());
        for t in [
            StormTrend::Storm,
            StormTrend::Falling,
            StormTrend::Steady,
            StormTrend::Rising,
        ] {
            assert!(t.is_measured());
        }
    }
}
