//! Numeral-face invariants. The table in `src/bignum.rs` is generated by
//! `scripts/gen_bignum.py`; these pin the properties the home clock hero
//! depends on so a regeneration that drops a glyph fails here, not on the
//! panel — plus the band renderer's compare-write contract, which is what
//! keeps a resting clock flushing zero lines.

use sharp_mip::{bignum, Framebuffer, HEIGHT, WIDTH};

#[test]
fn every_glyph_has_ink_and_no_two_collide() {
    let mut seen: Vec<&[[u8; bignum::BIGNUM_ROW_BYTES]; bignum::BIGNUM_HEIGHT]> = Vec::new();
    for (i, glyph) in bignum::BIGNUM.iter().enumerate() {
        assert!(
            glyph.iter().any(|row| row.iter().any(|&b| b != 0)),
            "glyph {:?} rasterised blank",
            bignum::BIGNUM_GLYPHS[i] as char
        );
        assert!(
            !seen.contains(&glyph),
            "glyph {:?} collides with an earlier glyph",
            bignum::BIGNUM_GLYPHS[i] as char
        );
        seen.push(glyph);
    }
}

#[test]
fn band_draw_stays_inside_its_rows_and_centres() {
    let mut fb = Framebuffer::new();
    fb.draw_bignum_band(32, "07:31");
    let inked: Vec<usize> = (0..HEIGHT)
        .filter(|&y| (0..WIDTH).any(|x| fb.pixel(x, y)))
        .collect();
    assert!(!inked.is_empty(), "clock drew nothing");
    assert!(
        *inked.first().unwrap() >= 32 && *inked.last().unwrap() < 32 + bignum::BIGNUM_HEIGHT,
        "ink escaped the band rows"
    );
    // 5 glyphs of 32 px centred on a 168 px panel: nothing in the first or
    // last 4 px.
    assert!((0..HEIGHT).all(|y| (0..4).all(|x| !fb.pixel(x, y))));
    assert!((0..HEIGHT).all(|y| (WIDTH - 4..WIDTH).all(|x| !fb.pixel(x, y))));
}

#[test]
fn redrawing_the_same_clock_dirties_nothing() {
    let mut fb = Framebuffer::new();
    fb.draw_bignum_band(32, "07:31");
    fb.clear_dirty();
    fb.draw_bignum_band(32, "07:31");
    assert_eq!(
        fb.dirty_count(),
        0,
        "an unchanged clock must flush no lines"
    );
    fb.draw_bignum_band(32, "07:32");
    assert!(fb.dirty_count() > 0, "a minute flip must dirty the band");
}

#[test]
fn band_redraw_erases_the_previous_text_without_a_clear_pass() {
    let mut fb = Framebuffer::new();
    fb.draw_bignum_band(32, "88:88");
    fb.draw_bignum_band(32, "--:--");
    // The dash carries no ink where the digit verticals were: if the band
    // renderer failed to compose the background, '8' residue would survive.
    let count = (32..32 + bignum::BIGNUM_HEIGHT)
        .map(|y| (0..WIDTH).filter(|&x| fb.pixel(x, y)).count())
        .sum::<usize>();
    let mut dashes = Framebuffer::new();
    dashes.draw_bignum_band(32, "--:--");
    let expected = (32..32 + bignum::BIGNUM_HEIGHT)
        .map(|y| (0..WIDTH).filter(|&x| dashes.pixel(x, y)).count())
        .sum::<usize>();
    assert_eq!(count, expected, "residue from the previous clock survived");
}
