//! Numeral-face invariants. The tables in `src/bignum.rs` are generated by
//! `scripts/gen_bignum.py`; these pin the properties the home clock hero and
//! the run-view glance heroes depend on so a regeneration that drops a glyph
//! fails here, not on the panel — plus the band renderers' compare-write
//! contract, which is what keeps a resting clock flushing zero lines.

use sharp_mip::{bignum, Framebuffer, HEIGHT, WIDTH};

#[test]
fn every_glyph_has_ink_and_no_two_collide() {
    let mut seen: Vec<&[[u8; bignum::BIGNUM_ROW_BYTES]; bignum::BIGNUM_HEIGHT]> = Vec::new();
    for (i, glyph) in bignum::BIGNUM.iter().enumerate() {
        assert!(
            glyph.iter().any(|row| row.iter().any(|&b| b != 0)),
            "glyph {:?} rasterised blank",
            bignum::BIGNUM_GLYPHS[i] as char
        );
        assert!(
            !seen.contains(&glyph),
            "glyph {:?} collides with an earlier glyph",
            bignum::BIGNUM_GLYPHS[i] as char
        );
        seen.push(glyph);
    }
}

#[test]
fn every_medium_glyph_has_ink_and_no_two_collide() {
    let mut seen: Vec<&[[u8; bignum::BIGNUM_MED_ROW_BYTES]; bignum::BIGNUM_MED_HEIGHT]> =
        Vec::new();
    for (i, glyph) in bignum::BIGNUM_MED.iter().enumerate() {
        assert!(
            glyph.iter().any(|row| row.iter().any(|&b| b != 0)),
            "medium glyph {:?} rasterised blank",
            bignum::BIGNUM_GLYPHS[i] as char
        );
        assert!(
            !seen.contains(&glyph),
            "medium glyph {:?} collides with an earlier glyph",
            bignum::BIGNUM_GLYPHS[i] as char
        );
        seen.push(glyph);
    }
}

#[test]
fn glyph_set_carries_the_decimal_point() {
    assert!(
        bignum::BIGNUM_GLYPHS.contains(&b'.'),
        "the run heroes' decimal point is missing from the glyph set"
    );
}

#[test]
fn band_draw_stays_inside_its_rows_and_centres() {
    let mut fb = Framebuffer::new();
    fb.draw_bignum_band(32, "07:31");
    let inked: Vec<usize> = (0..HEIGHT)
        .filter(|&y| (0..WIDTH).any(|x| fb.pixel(x, y)))
        .collect();
    assert!(!inked.is_empty(), "clock drew nothing");
    assert!(
        *inked.first().unwrap() >= 32 && *inked.last().unwrap() < 32 + bignum::BIGNUM_HEIGHT,
        "ink escaped the band rows"
    );
    // 5 glyphs of 32 px centred on a 168 px panel: nothing in the first or
    // last 4 px.
    assert!((0..HEIGHT).all(|y| (0..4).all(|x| !fb.pixel(x, y))));
    assert!((0..HEIGHT).all(|y| (WIDTH - 4..WIDTH).all(|x| !fb.pixel(x, y))));
}

#[test]
fn redrawing_the_same_clock_dirties_nothing() {
    let mut fb = Framebuffer::new();
    fb.draw_bignum_band(32, "07:31");
    fb.clear_dirty();
    fb.draw_bignum_band(32, "07:31");
    assert_eq!(
        fb.dirty_count(),
        0,
        "an unchanged clock must flush no lines"
    );
    fb.draw_bignum_band(32, "07:32");
    assert!(fb.dirty_count() > 0, "a minute flip must dirty the band");
}

#[test]
fn band_redraw_erases_the_previous_text_without_a_clear_pass() {
    let mut fb = Framebuffer::new();
    fb.draw_bignum_band(32, "88:88");
    fb.draw_bignum_band(32, "--:--");
    // The dash carries no ink where the digit verticals were: if the band
    // renderer failed to compose the background, '8' residue would survive.
    let count = (32..32 + bignum::BIGNUM_HEIGHT)
        .map(|y| (0..WIDTH).filter(|&x| fb.pixel(x, y)).count())
        .sum::<usize>();
    let mut dashes = Framebuffer::new();
    dashes.draw_bignum_band(32, "--:--");
    let expected = (32..32 + bignum::BIGNUM_HEIGHT)
        .map(|y| (0..WIDTH).filter(|&x| dashes.pixel(x, y)).count())
        .sum::<usize>();
    assert_eq!(count, expected, "residue from the previous clock survived");
}

// Bounding box of the ink inside an x-range of the hero band at y0 = 0.
fn ink_box(fb: &Framebuffer, x0: usize, x1: usize) -> Option<(usize, usize)> {
    let ys: Vec<usize> = (0..bignum::BIGNUM_HEIGHT)
        .filter(|&y| (x0..x1).any(|x| fb.pixel(x, y)))
        .collect();
    Some((*ys.first()?, *ys.last()?))
}

#[test]
fn hero_splits_at_the_point_big_head_medium_tail_shared_baseline() {
    let mut fb = Framebuffer::new();
    fb.draw_bignum_hero(0, "32.40");
    // "32" in the 32x48 face (x 0..64), ".40" in the 16x32 face (x 64..112).
    let (big_top, big_bottom) = ink_box(&fb, 0, 64).expect("big head drew nothing");
    let (med_top, med_bottom) = ink_box(&fb, 64, 112).expect("medium tail drew nothing");
    assert_eq!(
        big_bottom, med_bottom,
        "the two faces must share a baseline"
    );
    assert!(
        med_top > big_top,
        "the medium digits sit lower than the big ones"
    );
    assert_eq!(ink_box(&fb, 112, WIDTH), None, "ink escaped the hero span");
}

#[test]
fn hero_splits_at_the_colon_for_pace() {
    let mut fb = Framebuffer::new();
    fb.draw_bignum_hero(0, "6:20");
    let (big_top, big_bottom) = ink_box(&fb, 0, 32).expect("big minutes drew nothing");
    let (med_top, med_bottom) = ink_box(&fb, 32, 80).expect("medium seconds drew nothing");
    assert_eq!(big_bottom, med_bottom);
    assert!(med_top > big_top);
    assert_eq!(ink_box(&fb, 80, WIDTH), None);
}

#[test]
fn hero_without_a_separator_renders_all_big() {
    let mut all_big = Framebuffer::new();
    all_big.draw_bignum_hero(0, "42");
    let mut band = Framebuffer::new();
    band.draw_bignum_band(0, "42");
    // The band centres 2 glyphs at x 52; the hero anchors them at x 0 — same
    // pixels, shifted.
    for y in 0..bignum::BIGNUM_HEIGHT {
        for x in 0..2 * bignum::BIGNUM_WIDTH {
            assert_eq!(all_big.pixel(x, y), band.pixel(x + 52, y), "at ({x},{y})");
        }
    }
}

#[test]
fn hero_redraw_is_stable_and_leaves_pixels_right_of_its_span_alone() {
    let mut fb = Framebuffer::new();
    // A marker pixel where the fuel-overdue tag lives (row 1's right cells):
    // the span-scoped compose must never clear it.
    fb.set_pixel(150, 20, true);
    fb.clear_dirty();
    fb.draw_bignum_hero(0, "32.40");
    assert!(
        fb.pixel(150, 20),
        "hero clobbered a pixel right of its span"
    );
    fb.clear_dirty();
    fb.draw_bignum_hero(0, "32.40");
    assert_eq!(fb.dirty_count(), 0, "an unchanged hero must flush no lines");
    fb.draw_bignum_hero(0, "32.41");
    assert!(fb.dirty_count() > 0, "a digit flip must dirty the band");
}

#[test]
fn hero_truncates_and_clips_without_panicking() {
    let mut fb = Framebuffer::new();
    fb.draw_bignum_hero(0, "99999999999.99"); // wider than the panel
    fb.draw_bignum_hero(HEIGHT - 10, "3.1"); // clips at the bottom
    fb.draw_bignum_hero(0, "abc"); // outside the glyph set: advances blank
}

#[test]
fn the_medium_hero_occupies_exactly_the_two_rows_a_doubled_hero_does() {
    let mut med = Framebuffer::new();
    med.draw_bignum_med_hero(0, "12:34");
    let mut doubled = Framebuffer::new();
    doubled.draw_text_2x(0, 0, "12:34");
    for (name, fb) in [("medium", &med), ("doubled", &doubled)] {
        let inked: Vec<usize> = (0..HEIGHT)
            .filter(|&y| (0..WIDTH).any(|x| fb.pixel(x, y)))
            .collect();
        assert!(!inked.is_empty(), "{name} hero drew nothing");
        assert!(
            *inked.last().unwrap() < bignum::BIGNUM_MED_HEIGHT,
            "{name} hero escaped the two-row band"
        );
    }
    // Same advance, so the two occupy the same columns: neither reaches past
    // 5 glyphs of 16 px.
    for fb in [&med, &doubled] {
        assert!((0..HEIGHT).all(|y| (5 * bignum::BIGNUM_MED_WIDTH..WIDTH).all(|x| !fb.pixel(x, y))));
    }
    // The medium face is the heavier of the two at the same cell size — that
    // is the whole reason to prefer it on a reflective panel with no backlight.
    let ink = |fb: &Framebuffer| {
        (0..HEIGHT)
            .map(|y| (0..WIDTH).filter(|&x| fb.pixel(x, y)).count())
            .sum::<usize>()
    };
    assert!(
        ink(&med) > ink(&doubled),
        "medium {} vs doubled {}",
        ink(&med),
        ink(&doubled)
    );
}

#[test]
fn the_medium_hero_leaves_the_state_tag_cells_alone_and_rests_clean() {
    let mut fb = Framebuffer::new();
    // A marker pixel where the right-aligned state tag lives on row 0.
    fb.set_pixel(WIDTH - 4, 8, true);
    fb.clear_dirty();
    fb.draw_bignum_med_hero(0, "142");
    assert!(
        fb.pixel(WIDTH - 4, 8),
        "medium hero clobbered the state tag's cells"
    );
    fb.clear_dirty();
    fb.draw_bignum_med_hero(0, "142");
    assert_eq!(fb.dirty_count(), 0, "an unchanged hero must flush no lines");
    fb.draw_bignum_med_hero(0, "143");
    assert!(fb.dirty_count() > 0, "a digit flip must dirty the band");
}

#[test]
fn the_medium_hero_truncates_and_clips_without_panicking() {
    let mut fb = Framebuffer::new();
    fb.draw_bignum_med_hero(0, "999999999999999999"); // wider than the panel
    fb.draw_bignum_med_hero(HEIGHT - 6, "1:02"); // clips at the bottom
    fb.draw_bignum_med_hero(0, "abc"); // outside the glyph set: advances blank
}

#[test]
fn the_numeral_faces_carry_no_sign_so_a_signed_hero_must_not_use_them() {
    // The Pacer / cut-off heroes are signed (`+0:42` ahead, `-1:05` behind).
    // Until a regeneration adds `+`, `watch_core::ui_frame::numeral_hero`
    // routes them to the text font; this is the driver-side half of that
    // contract, so adding the glyph fails here and forces the pair to be
    // reconsidered together.
    assert!(!bignum::BIGNUM_GLYPHS.contains(&b'+'));
    assert!(bignum::BIGNUM_GLYPHS.contains(&b'-'));
}
