//! Font-table invariants. The table in `src/font.rs` is generated by
//! `scripts/gen_font.py`; these tests pin the properties a glance page depends
//! on so a regeneration that silently drops a stroke fails here instead of on
//! the panel.
//!
//! History: rendering the strip straight at 8x16 point-sampled the outline, so
//! strokes narrower than a pixel vanished. '+' came out byte-identical to '-'
//! and '|' came out blank (byte-identical to space) — a signed pacer delta
//! (`+0:42` ahead vs `-1:05` behind) and the `VERT +gain -loss` row both read
//! the same either way. The generator now area-samples an oversampled raster.

use sharp_mip::{font, Framebuffer};

fn glyph(ch: u8) -> &'static [u8; font::GLYPH_HEIGHT] {
    &font::FONT[(ch - font::FIRST_CHAR) as usize]
}

/// Number of rows carrying at least one ink pixel.
fn inked_rows(g: &[u8; font::GLYPH_HEIGHT]) -> usize {
    g.iter().filter(|&&r| r != 0).count()
}

/// Longest run of horizontally adjacent ink pixels in any single row.
fn longest_horizontal_run(g: &[u8; font::GLYPH_HEIGHT]) -> usize {
    let mut best = 0;
    for &row in g {
        let (mut run, mut cur) = (0, 0);
        for x in 0..font::GLYPH_WIDTH {
            cur = if row >> x & 1 != 0 { cur + 1 } else { 0 };
            run = run.max(cur);
        }
        best = best.max(run);
    }
    best
}

/// Longest run of vertically adjacent ink pixels in any single column.
fn longest_vertical_run(g: &[u8; font::GLYPH_HEIGHT]) -> usize {
    let mut best = 0;
    for x in 0..font::GLYPH_WIDTH {
        let (mut run, mut cur) = (0, 0);
        for &row in g {
            cur = if row >> x & 1 != 0 { cur + 1 } else { 0 };
            run = run.max(cur);
        }
        best = best.max(run);
    }
    best
}

#[test]
fn plus_is_not_a_dash() {
    assert_ne!(
        glyph(b'+'),
        glyph(b'-'),
        "'+' and '-' render identically — a signed delta is unreadable"
    );
}

#[test]
fn plus_has_both_a_bar_and_a_stem() {
    let plus = glyph(b'+');
    // A bar alone (what the old table had) is a single inked row.
    assert!(
        inked_rows(plus) > 1,
        "'+' occupies only {} row(s) — the vertical stem is missing",
        inked_rows(plus)
    );
    // The crossbar: '-' is 6px wide, so the bar of '+' must be too.
    assert!(
        longest_horizontal_run(plus) >= 4,
        "'+' has no horizontal crossbar (longest run {})",
        longest_horizontal_run(plus)
    );
    // The stem must be tall enough to read as a cross at 1x, not as a dot.
    assert!(
        longest_vertical_run(plus) >= 4,
        "'+' has no vertical stem (longest run {})",
        longest_vertical_run(plus)
    );
    // The stem has to actually cross the bar, otherwise it reads as two marks.
    let bar_row = plus
        .iter()
        .position(|&r| r.count_ones() >= 4)
        .expect("'+' has a crossbar row");
    let stem_cols: Vec<usize> = (0..font::GLYPH_WIDTH)
        .filter(|&x| {
            let above = plus[..bar_row].iter().any(|&r| r >> x & 1 != 0);
            let below = plus[bar_row + 1..].iter().any(|&r| r >> x & 1 != 0);
            above && below
        })
        .collect();
    assert!(
        !stem_cols.is_empty(),
        "'+' stem does not cross its bar (ink above and below in no column)"
    );
}

#[test]
fn pipe_is_a_vertical_stroke_not_blank() {
    let pipe = glyph(b'|');
    assert_ne!(pipe, glyph(b' '), "'|' renders blank, same as space");
    assert!(
        longest_vertical_run(pipe) >= 8,
        "'|' is not a full-height stroke (longest run {})",
        longest_vertical_run(pipe)
    );
}

#[test]
fn bang_is_a_stem_over_a_dot_not_a_second_colon() {
    // The same lost-hairline failure as '+' and '|', one step short of the
    // collision that would have caught it: '!' kept its top serif and its dot
    // but lost the stem between them, packing to two short marks — a colon with
    // its upper dot raised a row. Distinct bytes, so `no_two_printable_chars_
    // share_a_bitmap` passed; indistinguishable on the panel, so every alert
    // banner opened `: DRINK` instead of `! DRINK`. The banner is this device's
    // loudest treatment and the bang is the whole of what marks it as an alert
    // rather than a label, so the shape is pinned here and not left to the
    // generator's collision test, which cannot see it.
    let bang = glyph(b'!');
    let colon = glyph(b':');
    assert_ne!(bang, colon, "'!' and ':' render identically");
    // A colon is two dots, so its tallest run is one dot tall. A bang has to
    // beat that outright, or the reader has only dot spacing to go on.
    assert!(
        longest_vertical_run(bang) > longest_vertical_run(colon),
        "'!' has no stem: its tallest vertical run is {} against the colon's \
         {} — it reads as punctuation, not as an alert",
        longest_vertical_run(bang),
        longest_vertical_run(colon)
    );
    // And the dot has to stay detached, or the stem runs to the baseline and
    // the bang reads as '|' — the other glyph it can collapse into.
    let gaps = bang.windows(2).filter(|w| w[0] != 0 && w[1] == 0).count();
    assert_eq!(
        gaps, 2,
        "'!' has {gaps} ink-to-blank transition(s), not the 2 a stem with a \
         detached dot below it makes"
    );
}

#[test]
fn horizontal_bar_glyphs_carry_one_consistent_weight() {
    // The bar glyphs are where a weight mismatch is most visible: '--' (the
    // absent-value marker) sits beside '=' and '_' on data rows all day. The
    // rasterised table shipped exactly that defect once — a repair pass
    // thickened '-' to a two-row wedge while '=' and '_' stayed single-row —
    // so the invariant is pinned shape-wise: each is a pure horizontal bar
    // (no ink outside its bar rows), and every bar in all three glyphs is the
    // same thickness. Exact positions are NOT pinned; those belong to the
    // digest-pinned source face, and re-pinning them here would only make a
    // deliberate face change fail twice.
    let bar_thicknesses = |g: &[u8; font::GLYPH_HEIGHT]| -> Vec<usize> {
        let mut runs = Vec::new();
        let mut run = 0;
        for &row in g {
            if row != 0 {
                run += 1;
            } else if run > 0 {
                runs.push(run);
                run = 0;
            }
        }
        if run > 0 {
            runs.push(run);
        }
        runs
    };
    let mut all_runs = Vec::new();
    for ch in [b'-', b'=', b'_'] {
        let g = glyph(ch);
        for &row in g.iter().filter(|&&r| r != 0) {
            let width = longest_horizontal_run(g);
            assert!(
                row.count_ones() as usize == width,
                "{:?} has a non-bar ink row (0x{row:02X})",
                ch as char
            );
        }
        let runs = bar_thicknesses(g);
        assert!(!runs.is_empty(), "{:?} is blank", ch as char);
        all_runs.extend(runs);
    }
    assert!(
        all_runs.windows(2).all(|w| w[0] == w[1]),
        "bar glyphs carry mixed weights: {all_runs:?} — '-', '=' and '_' \
         must read as one family"
    );
}

#[test]
fn no_two_printable_chars_share_a_bitmap() {
    // Space is the only legitimately blank glyph; every other printable char
    // must be distinguishable from every other one. A collision means the
    // rasteriser dropped a stroke (how '+'=='-' and '|'==' ' got in).
    let mut collisions: Vec<String> = Vec::new();
    for (i, a) in font::FONT.iter().enumerate() {
        for (j, b) in font::FONT.iter().enumerate().skip(i + 1) {
            if a == b {
                let (ca, cb) = (font::FIRST_CHAR + i as u8, font::FIRST_CHAR + j as u8);
                collisions.push(format!("{:?} == {:?}", ca as char, cb as char));
            }
        }
    }
    assert!(
        collisions.is_empty(),
        "printable chars share a bitmap: {}",
        collisions.join(", ")
    );
}

/// Ink extents of a framebuffer region, as (widest horizontal run, tallest
/// vertical run) — the same "is it a cross?" shape check as on the raw glyph,
/// applied to what actually lands on the panel.
fn rendered_extents(fb: &Framebuffer, x0: usize, y0: usize, w: usize, h: usize) -> (usize, usize) {
    let mut widest = 0;
    for y in y0..y0 + h {
        let (mut run, mut cur) = (0, 0);
        for x in x0..x0 + w {
            cur = if fb.pixel(x, y) { cur + 1 } else { 0 };
            run = run.max(cur);
        }
        widest = widest.max(run);
    }
    let mut tallest = 0;
    for x in x0..x0 + w {
        let (mut run, mut cur) = (0, 0);
        for y in y0..y0 + h {
            cur = if fb.pixel(x, y) { cur + 1 } else { 0 };
            run = run.max(cur);
        }
        tallest = tallest.max(run);
    }
    (widest, tallest)
}

#[test]
fn plus_reads_as_a_cross_at_every_scale() {
    // draw_text/_2x pixel-replicate the same 8x16 glyph, so a correct glyph
    // scales exactly — but check each renderer really consumes it, and that
    // '+' stays distinct from '-' at every scale a page can use.
    for (scale, draw) in [
        (
            1usize,
            Framebuffer::draw_text as fn(&mut Framebuffer, usize, usize, &str),
        ),
        (2, Framebuffer::draw_text_2x),
    ] {
        let (w, h) = (font::GLYPH_WIDTH * scale, font::GLYPH_HEIGHT * scale);

        let mut plus = Framebuffer::new();
        draw(&mut plus, 0, 0, "+");
        let (bar, stem) = rendered_extents(&plus, 0, 0, w, h);
        assert!(
            bar >= 4 * scale && stem >= 4 * scale,
            "'+' at {scale}x is not a cross: bar {bar}px, stem {stem}px"
        );

        let mut dash = Framebuffer::new();
        draw(&mut dash, 0, 0, "-");
        let (_, dash_stem) = rendered_extents(&dash, 0, 0, w, h);
        assert!(
            stem >= 2 * dash_stem,
            "'+' at {scale}x has no more vertical extent than '-' ({stem}px vs {dash_stem}px)"
        );
        assert!(
            (0..h).any(|y| (0..w).any(|x| plus.pixel(x, y) != dash.pixel(x, y))),
            "'+' and '-' are indistinguishable at {scale}x"
        );
    }
}

#[test]
fn no_two_printable_small_chars_share_a_bitmap() {
    // The same gate as the 8x16 table, over the 6x12 label face: space is
    // the only legitimately blank glyph, everything else must be tellable
    // apart on the panel.
    use sharp_mip::font_small;
    let mut collisions: Vec<String> = Vec::new();
    for (i, a) in font_small::FONT.iter().enumerate() {
        for (j, b) in font_small::FONT.iter().enumerate().skip(i + 1) {
            if a == b {
                let (ca, cb) = (
                    font_small::FIRST_CHAR + i as u8,
                    font_small::FIRST_CHAR + j as u8,
                );
                collisions.push(format!("{:?} == {:?}", ca as char, cb as char));
            }
        }
    }
    assert!(
        collisions.is_empty(),
        "small chars share a bitmap: {}",
        collisions.join(", ")
    );
}
