//! Icon-table invariants. The table in `src/icons.rs` is generated by
//! `scripts/gen_icons.py` from the SVG sources under `icons/`, through the same
//! Inkscape -> ImageMagick rasteriser as the font; these tests pin the
//! properties a glance page depends on so a regeneration that flattens an icon
//! fails here instead of on the panel.
//!
//! History: the font hit exactly this. Rasterising at 8x16 point-sampled the
//! outline, so strokes narrower than a pixel vanished — '+' came out
//! byte-identical to '-' and '|' came out blank. It took two sim passes to
//! notice, because a collision does not look broken, it looks like the wrong
//! icon.
//!
//! Icons carry that risk in a worse form. `Heart`/`HeartSmall` and
//! `SatSearch0`/`SatSearch1`/`Satellite` are deliberately-similar frames of an
//! animation, so a collision between two of them is not a misdrawn icon — it is
//! a beat of the animation that silently stops moving, on a panel with no
//! refresh cue of its own to say the watch is still alive.

use sharp_mip::{Framebuffer, Icon, ICON_SIZE};

fn ink(icon: Icon) -> usize {
    icon.bitmap()
        .iter()
        .flatten()
        .map(|b| b.count_ones() as usize)
        .sum()
}

/// Maximal runs of ink down one column of an icon — how many separate bands a
/// ray drawn through that column crosses.
fn ink_bands_in_column(icon: Icon, x: usize) -> usize {
    let mut bands = 0;
    let mut prev = false;
    for row in icon.bitmap() {
        let lit = row[x / 8] & (1 << (x % 8)) != 0;
        if lit && !prev {
            bands += 1;
        }
        prev = lit;
    }
    bands
}

#[test]
fn every_icon_has_ink() {
    for icon in Icon::ALL {
        assert!(
            ink(icon) > 0,
            "{icon:?} rasterised blank — the cell draws nothing at all"
        );
    }
}

#[test]
fn no_two_icons_share_a_bitmap() {
    // A collision means the rasteriser flattened away whatever distinguished
    // them, which is how '+' == '-' got into the font.
    let mut collisions: Vec<String> = Vec::new();
    for (i, a) in Icon::ALL.iter().enumerate() {
        for b in Icon::ALL.iter().skip(i + 1) {
            if a.bitmap() == b.bitmap() {
                collisions.push(format!("{a:?} == {b:?}"));
            }
        }
    }
    assert!(
        collisions.is_empty(),
        "icons share a bitmap: {}",
        collisions.join(", ")
    );
}

#[test]
fn the_heartbeat_animation_has_two_distinguishable_frames() {
    // The HR row alternates these every frame to show a live pulse. Equal
    // bitmaps read as a frozen heart, which is exactly what a dead sensor looks
    // like — the animation would be lying in the one direction that matters.
    assert_ne!(
        Icon::Heart.bitmap(),
        Icon::HeartSmall.bitmap(),
        "the heartbeat frames are identical — the pulse never moves"
    );
    assert!(
        ink(Icon::Heart) > ink(Icon::HeartSmall),
        "the small heart ({} px) is not smaller than the big one ({} px)",
        ink(Icon::HeartSmall),
        ink(Icon::Heart)
    );
}

#[test]
fn the_satellite_search_animation_has_three_distinguishable_frames() {
    // The acquiring-a-fix cycle: one arc, two arcs, three. Two equal frames
    // stall the animation, and a runner waiting on GPS at a start line reads a
    // stalled search as a hung watch.
    let frames = [Icon::SatSearch0, Icon::SatSearch1, Icon::Satellite];
    for (i, a) in frames.iter().enumerate() {
        for b in frames.iter().skip(i + 1) {
            assert_ne!(
                a.bitmap(),
                b.bitmap(),
                "{a:?} and {b:?} are the same frame — the search stops moving"
            );
        }
    }
    assert!(
        ink(Icon::SatSearch0) < ink(Icon::SatSearch1),
        "the search does not grow from frame 0 to frame 1"
    );
    assert!(
        ink(Icon::SatSearch1) < ink(Icon::Satellite),
        "the search does not grow from frame 1 to the acquired dish"
    );
}

#[test]
fn each_search_frame_shows_its_arcs_as_separate_bands() {
    // Growing ink is not the same as growing legibility, and the difference is
    // what the first version of this family got wrong: its three arcs all began
    // at the anchor dot instead of being concentric about it, so near the origin
    // they overlapped into one diagonal wedge and only separated at their far
    // tips. Every check above passed on it — the frames were distinct, the ink
    // grew — while on the panel all three read as the same hook. Since § 361 put
    // this glyph on the GPS row of every page, that is the most-repeated
    // graphic in the UI saying nothing about how many satellites are held.
    //
    // The arcs are concentric about the dot, so the icon's vertical centre line
    // is a ray outward from it and has to cross one band per arc plus the dot
    // itself. Counting bands is what distinguishes drawn-apart from merged;
    // ink totals cannot see the difference.
    for (icon, arcs) in [
        (Icon::SatSearch0, 1),
        (Icon::SatSearch1, 2),
        (Icon::Satellite, 3),
    ] {
        let bands = ink_bands_in_column(icon, ICON_SIZE / 2);
        assert_eq!(
            bands,
            arcs + 1,
            "{icon:?} crosses {bands} ink bands up its centre line, not the \
             {} its {arcs} arc(s) plus the anchor dot need — the arcs have \
             merged into each other or into the dot",
            arcs + 1
        );
    }
}

#[test]
fn every_icon_reaches_the_panel() {
    // The table having ink is not the same as the blit putting any of it on the
    // panel: a bitmap whose ink all sat outside the drawn cells would pass the
    // table checks and still render an empty square.
    for icon in Icon::ALL {
        let mut fb = Framebuffer::new();
        fb.draw_icon(0, 0, icon);
        let drawn = (0..ICON_SIZE)
            .flat_map(|y| (0..ICON_SIZE).map(move |x| (x, y)))
            .filter(|&(x, y)| fb.pixel(x, y))
            .count();
        assert_eq!(
            drawn,
            ink(icon),
            "{icon:?} lost ink between its table entry and the panel"
        );
    }
}
