//! Icon-table invariants. The table in `src/icons.rs` is generated by
//! `scripts/gen_icons.py` from the SVG sources under `icons/`, through the same
//! Inkscape -> ImageMagick rasteriser as the font; these tests pin the
//! properties a glance page depends on so a regeneration that flattens an icon
//! fails here instead of on the panel.
//!
//! History: the font hit exactly this. Rasterising at 8x16 point-sampled the
//! outline, so strokes narrower than a pixel vanished — '+' came out
//! byte-identical to '-' and '|' came out blank. It took two sim passes to
//! notice, because a collision does not look broken, it looks like the wrong
//! icon.
//!
//! Icons carry that risk in a worse form. `Heart`/`HeartSmall` and
//! `SatSearch0`/`SatSearch1`/`Satellite` are deliberately-similar frames of an
//! animation, so a collision between two of them is not a misdrawn icon — it is
//! a beat of the animation that silently stops moving, on a panel with no
//! refresh cue of its own to say the watch is still alive.

use sharp_mip::{Framebuffer, Icon, ICON_SIZE};

fn ink(icon: Icon) -> usize {
    icon.bitmap()
        .iter()
        .flatten()
        .map(|b| b.count_ones() as usize)
        .sum()
}

#[test]
fn every_icon_has_ink() {
    for icon in Icon::ALL {
        assert!(
            ink(icon) > 0,
            "{icon:?} rasterised blank — the cell draws nothing at all"
        );
    }
}

#[test]
fn no_two_icons_share_a_bitmap() {
    // A collision means the rasteriser flattened away whatever distinguished
    // them, which is how '+' == '-' got into the font.
    let mut collisions: Vec<String> = Vec::new();
    for (i, a) in Icon::ALL.iter().enumerate() {
        for b in Icon::ALL.iter().skip(i + 1) {
            if a.bitmap() == b.bitmap() {
                collisions.push(format!("{a:?} == {b:?}"));
            }
        }
    }
    assert!(
        collisions.is_empty(),
        "icons share a bitmap: {}",
        collisions.join(", ")
    );
}

#[test]
fn the_heartbeat_animation_has_two_distinguishable_frames() {
    // The HR row alternates these every frame to show a live pulse. Equal
    // bitmaps read as a frozen heart, which is exactly what a dead sensor looks
    // like — the animation would be lying in the one direction that matters.
    assert_ne!(
        Icon::Heart.bitmap(),
        Icon::HeartSmall.bitmap(),
        "the heartbeat frames are identical — the pulse never moves"
    );
    assert!(
        ink(Icon::Heart) > ink(Icon::HeartSmall),
        "the small heart ({} px) is not smaller than the big one ({} px)",
        ink(Icon::HeartSmall),
        ink(Icon::Heart)
    );
}

#[test]
fn the_satellite_search_animation_has_three_distinguishable_frames() {
    // The acquiring-a-fix cycle: bare dish, one arc, two arcs. Two equal frames
    // stall the animation, and a runner waiting on GPS at a start line reads a
    // stalled search as a hung watch.
    let frames = [Icon::SatSearch0, Icon::SatSearch1, Icon::Satellite];
    for (i, a) in frames.iter().enumerate() {
        for b in frames.iter().skip(i + 1) {
            assert_ne!(
                a.bitmap(),
                b.bitmap(),
                "{a:?} and {b:?} are the same frame — the search stops moving"
            );
        }
    }
    assert!(
        ink(Icon::SatSearch0) < ink(Icon::SatSearch1),
        "the search does not grow from frame 0 to frame 1"
    );
    assert!(
        ink(Icon::SatSearch1) < ink(Icon::Satellite),
        "the search does not grow from frame 1 to the acquired dish"
    );
}

#[test]
fn every_icon_reaches_the_panel() {
    // The table having ink is not the same as the blit putting any of it on the
    // panel: a bitmap whose ink all sat outside the drawn cells would pass the
    // table checks and still render an empty square.
    for icon in Icon::ALL {
        let mut fb = Framebuffer::new();
        fb.draw_icon(0, 0, icon);
        let drawn = (0..ICON_SIZE)
            .flat_map(|y| (0..ICON_SIZE).map(move |x| (x, y)))
            .filter(|&(x, y)| fb.pixel(x, y))
            .count();
        assert_eq!(
            drawn,
            ink(icon),
            "{icon:?} lost ink between its table entry and the panel"
        );
    }
}
