name: watch_wear
description: Run app - Wear OS target.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  core_models:
    path: ../../packages/core_models
  run_recorder:
    path: ../../packages/run_recorder
  api_client:
    path: ../../packages/api_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
