import { expect, test } from '@playwright/test';

import { USER_A } from '../fixtures/users';

/**
 * /plans/[id] — plan-detail surface. Split out from plans/list.spec.ts
 * now that the surface has depth: progress ring, today card, multi-
 * week grid, workout-day editor modal, and the Edit-plan meta dialog.
 *
 * The seed provisions a single active training_plan ("Sydney Half
 * 2026", id `a1a1eada-aaaa-…`) with a multi-week grid generated by
 * the plan generator. Tests here pin behaviour against that plan.
 *
 * Future depth: Edit-plan meta dialog (PlanMetaEditor), workout
 * complete + uncomplete, drill into /plans/[id]/workouts/[wid].
 */

test.describe('/plans/[id]', () => {
	test.use({ storageState: USER_A.storageStatePath });

	test('Sydney Half plan renders multi-week grid + clicking a day opens the workout editor', async ({
		page
	}) => {
		// Drill in via the list page so we don't have to hardcode the
		// plan id — fetchActivePlan + slug-style routing means the URL
		// is /plans/<uuid>.
		await page.goto('/plans');
		await page.getByRole('link', { name: /Sydney Half 2026/ }).click();
		await expect(page).toHaveURL(/\/plans\/[0-9a-f-]+$/);

		// h1 = plan name proves the row loaded.
		await expect(
			page.getByRole('heading', { level: 1, name: /Sydney Half 2026/ })
		).toBeVisible({ timeout: 10_000 });

		// The plan generator emits multiple weeks (this plan is at
		// least 8 weeks per the seed). >=2 .week articles is the
		// load-bearing assertion — collapsing to a single week would
		// mean fetchPlanWeeks lost rows or the workoutsByWeek bucket
		// regressed.
		const weeks = page.locator('.weeks .week');
		await expect(weeks.first()).toBeVisible({ timeout: 10_000 });
		expect(await weeks.count()).toBeGreaterThanOrEqual(2);

		// Each non-rest day is a button (`.day-link`) that sets
		// `editing = wo`, mounting the WorkoutEditor inside a Modal.
		// Click the first day-link and verify a modal appears.
		await page.locator('.day-link').first().click();
		await expect(page.locator('.modal')).toBeVisible({ timeout: 5_000 });

		// Close without changes (idempotency).
		await page.locator('.modal-close').click();
		await expect(page.locator('.modal')).toHaveCount(0);
	});
});
