import { expect, test } from '@playwright/test';

import { getAdminClient } from '../fixtures/local-supabase';
import { USER_A } from '../fixtures/users';

/**
 * /plans/[id] — plan-detail surface. Split out from plans/list.spec.ts
 * now that the surface has depth: progress ring, today card, multi-
 * week grid, workout-day editor modal, and the Edit-plan meta dialog.
 *
 * The seed provisions a single active training_plan ("Sydney Half
 * 2026", id `a1a1eada-aaaa-…`) with a multi-week grid generated by
 * the plan generator. Tests here pin behaviour against that plan.
 *
 * Future depth: Edit-plan meta dialog (PlanMetaEditor), workout
 * complete + uncomplete, drill into /plans/[id]/workouts/[wid].
 */

test.describe('/plans/[id]', () => {
	test.use({ storageState: USER_A.storageStatePath });

	test('Edit-plan meta dialog: rename → Save persists across reload, restore', async ({
		page
	}) => {
		// Edit-plan opens PlanMetaEditor (Modal-hosted) which exposes
		// name / days-per-week / goal-time / notes / rules. We pin the
		// rename round-trip — change Name, Save, reload, assert the
		// h1 reflects the new name, then restore. updatePlan in
		// data.ts is the write path.
		await page.goto('/plans');
		await page.getByRole('link', { name: /Sydney Half 2026/ }).click();
		await expect(page.getByRole('heading', { level: 1, name: /Sydney Half 2026/ }))
			.toBeVisible({ timeout: 10_000 });

		const restored = 'Sydney Half 2026';
		const renamed = `e2e-renamed ${Date.now()}`;

		// Open the editor.
		await page.getByRole('button', { name: /Edit plan/ }).click();
		const modal = page.locator('.modal');
		await expect(modal).toBeVisible({ timeout: 5_000 });
		// First text input in the modal is Name.
		const nameInput = modal.locator('input[type="text"]').first();
		await expect(nameInput).toHaveValue(restored);
		await nameInput.fill(renamed);
		await modal.getByRole('button', { name: 'Save', exact: true }).click();
		await expect(modal).toHaveCount(0);

		// h1 reflects the new name immediately (load() ran in onSaved).
		await expect(page.getByRole('heading', { level: 1, name: renamed }))
			.toBeVisible({ timeout: 10_000 });

		// Reload — the new value persisted server-side, not just in
		// memory.
		await page.reload();
		await expect(page.getByRole('heading', { level: 1, name: renamed }))
			.toBeVisible({ timeout: 10_000 });

		// Restore the seeded name so the rest of the suite sees it.
		await page.getByRole('button', { name: /Edit plan/ }).click();
		await expect(page.locator('.modal')).toBeVisible({ timeout: 5_000 });
		await page.locator('.modal input[type="text"]').first().fill(restored);
		await page.locator('.modal').getByRole('button', { name: 'Save', exact: true }).click();
		await expect(page.locator('.modal')).toHaveCount(0);
		await expect(page.getByRole('heading', { level: 1, name: restored }))
			.toBeVisible({ timeout: 10_000 });
	});

	test('Sydney Half plan renders multi-week grid + clicking a day opens the workout editor', async ({
		page
	}) => {
		// Drill in via the list page so we don't have to hardcode the
		// plan id — fetchActivePlan + slug-style routing means the URL
		// is /plans/<uuid>.
		await page.goto('/plans');
		await page.getByRole('link', { name: /Sydney Half 2026/ }).click();
		await expect(page).toHaveURL(/\/plans\/[0-9a-f-]+$/);

		// h1 = plan name proves the row loaded.
		await expect(
			page.getByRole('heading', { level: 1, name: /Sydney Half 2026/ })
		).toBeVisible({ timeout: 10_000 });

		// The plan generator emits multiple weeks (this plan is at
		// least 8 weeks per the seed). >=2 .week articles is the
		// load-bearing assertion — collapsing to a single week would
		// mean fetchPlanWeeks lost rows or the workoutsByWeek bucket
		// regressed.
		const weeks = page.locator('.weeks .week');
		await expect(weeks.first()).toBeVisible({ timeout: 10_000 });
		expect(await weeks.count()).toBeGreaterThanOrEqual(2);

		// Each non-rest day is a button (`.day-link`) that sets
		// `editing = wo`, mounting the WorkoutEditor inside a Modal.
		// Click the first day-link and verify a modal appears.
		await page.locator('.day-link').first().click();
		await expect(page.locator('.modal')).toBeVisible({ timeout: 5_000 });

		// Close without changes (idempotency).
		await page.locator('.modal-close').click();
		await expect(page.locator('.modal')).toHaveCount(0);
	});

	test('publish-as-template: pick a club → Publish → club gets the new template', async ({
		page
	}) => {
		// publishPlanAsTemplate clones the source plan into a new
		// `is_template=true, club_id=<club>` sibling. The source plan
		// row stays put; the new row appears under the club's
		// Templates tab. Cleanup deletes the cloned template via
		// service-role.
		const SYDNEY_RUN_CLUB_ID = 'c1111111-0000-0000-0000-000000000001';

		await page.goto('/plans');
		await page.getByRole('link', { name: /Sydney Half 2026/ }).click();
		await expect(page).toHaveURL(/\/plans\/[0-9a-f-]+$/);

		// Pick the club + click Publish. The publish-row is gated on
		// `!plan.is_template && adminClubs.length > 0` — runner owns
		// three seeded clubs so the dropdown is populated.
		const publishRow = page.locator('.publish-row');
		await expect(publishRow).toBeVisible({ timeout: 10_000 });
		await publishRow.locator('select').selectOption(SYDNEY_RUN_CLUB_ID);
		await publishRow.getByRole('button', { name: 'Publish' }).click();

		// The handler shows a toast on success; the dropdown resets to
		// the placeholder. Wait for the reset as a proxy for the await.
		await expect(publishRow.locator('select')).toHaveValue('', {
			timeout: 10_000
		});

		// The cloned template now lives under Sydney Run Club's
		// Templates tab. Drill in via the canonical UI.
		await page.goto('/clubs/sydney-run-club');
		await expect(
			page.getByRole('heading', { level: 1, name: 'Sydney Run Club' })
		).toBeVisible({ timeout: 10_000 });
		await page.getByRole('button', { name: /^Templates/ }).click();
		await expect(
			page.locator('.template-row', { hasText: 'Sydney Half 2026' })
		).toBeVisible({ timeout: 10_000 });

		// Cleanup — find the cloned template id (any plan row with
		// is_template=true + club_id=<sydney> + name=<source>) and
		// delete it. plan_weeks + plan_workouts cascade.
		const admin = getAdminClient();
		const { data: rows } = await admin
			.from('training_plans')
			.select('id')
			.eq('is_template', true)
			.eq('club_id', SYDNEY_RUN_CLUB_ID)
			.eq('name', 'Sydney Half 2026');
		for (const r of rows ?? []) {
			await admin.from('training_plans').delete().eq('id', (r as { id: string }).id);
		}
	});

	test('publish-as-template deep clone: plan_weeks + plan_workouts copied, completion fields reset', async ({
		page
	}) => {
		// Backend boundary: publishPlanAsTemplate doesn't just copy
		// the training_plans row — it iterates plan_weeks and
		// plan_workouts and deep-clones every child. Critically, it
		// must RESET completion fields on the clone (manually_completed,
		// completed_run_id) — otherwise a community template would
		// arrive with the source author's completed-workout state
		// pre-filled, which is a privacy + correctness leak.
		// pgtap can pin the SQL; this test pins the CANONICAL UI
		// path through publishPlanAsTemplate against regressions in
		// the data layer (wrong column list, missing reset, off-by-
		// one on the week loop).
		const SYDNEY_RUN_CLUB_ID = 'c1111111-0000-0000-0000-000000000001';
		const SYDNEY_HALF_PLAN_ID = 'a1a1eada-aaaa-0000-0000-000000000001';
		const admin = getAdminClient();

		// Snapshot: how many weeks + workouts does the source plan
		// have? The clone must end up with the same counts.
		const { data: srcWeeks } = await admin
			.from('plan_weeks')
			.select('id')
			.eq('plan_id', SYDNEY_HALF_PLAN_ID);
		const srcWeekIds = (srcWeeks ?? []).map((w) => (w as { id: string }).id);
		expect(srcWeekIds.length).toBeGreaterThan(0);
		const { count: srcWorkoutCount } = await admin
			.from('plan_workouts')
			.select('id', { count: 'exact', head: true })
			.in('week_id', srcWeekIds);
		expect(srcWorkoutCount).toBeGreaterThan(0);

		// Drive the publish UI.
		await page.goto(`/plans/${SYDNEY_HALF_PLAN_ID}`);
		const publishRow = page.locator('.publish-row');
		await expect(publishRow).toBeVisible({ timeout: 10_000 });
		await publishRow.locator('select').selectOption(SYDNEY_RUN_CLUB_ID);
		await publishRow.getByRole('button', { name: 'Publish' }).click();
		await expect(publishRow.locator('select')).toHaveValue('', {
			timeout: 10_000
		});

		// Find the cloned template.
		const { data: clones } = await admin
			.from('training_plans')
			.select('id, status, is_template')
			.eq('is_template', true)
			.eq('club_id', SYDNEY_RUN_CLUB_ID)
			.eq('name', 'Sydney Half 2026');
		expect(clones?.length).toBe(1);
		const cloneId = (clones![0] as { id: string }).id;

		try {
			// Status flag invariants: the clone's row exists with
			// is_template=true and a non-active status (the migration
			// CHECK forbids active+template; setPlanIsTemplate sets
			// status='completed' on flag).
			expect((clones![0] as { is_template: boolean }).is_template).toBe(true);
			expect((clones![0] as { status: string }).status).not.toBe('active');

			// Same number of plan_weeks rows as the source.
			const { data: cloneWeeks } = await admin
				.from('plan_weeks')
				.select('id')
				.eq('plan_id', cloneId);
			const cloneWeekIds = (cloneWeeks ?? []).map((w) => (w as { id: string }).id);
			expect(cloneWeekIds.length).toBe(srcWeekIds.length);

			// Same number of plan_workouts rows as the source, and
			// EVERY clone's completion fields are reset.
			const { data: cloneWorkouts } = await admin
				.from('plan_workouts')
				.select('manually_completed, completed_run_id, completed_at')
				.in('week_id', cloneWeekIds);
			expect(cloneWorkouts?.length).toBe(srcWorkoutCount);
			for (const w of cloneWorkouts ?? []) {
				const row = w as {
					manually_completed: boolean;
					completed_run_id: string | null;
					completed_at: string | null;
				};
				expect(row.manually_completed).toBe(false);
				expect(row.completed_run_id).toBeNull();
				expect(row.completed_at).toBeNull();
			}
		} finally {
			// Sweep — plan_weeks + plan_workouts cascade off the
			// training_plans delete.
			await admin.from('training_plans').delete().eq('id', cloneId);
		}
	});
});
