import { expect, test } from '@playwright/test';

import { USER_A } from '../fixtures/users';

/**
 * /plans/[id] — plan-detail surface. Split out from plans/list.spec.ts
 * now that the surface has depth: progress ring, today card, multi-
 * week grid, workout-day editor modal, and the Edit-plan meta dialog.
 *
 * The seed provisions a single active training_plan ("Sydney Half
 * 2026", id `a1a1eada-aaaa-…`) with a multi-week grid generated by
 * the plan generator. Tests here pin behaviour against that plan.
 *
 * Future depth: Edit-plan meta dialog (PlanMetaEditor), workout
 * complete + uncomplete, drill into /plans/[id]/workouts/[wid].
 */

test.describe('/plans/[id]', () => {
	test.use({ storageState: USER_A.storageStatePath });

	test('Edit-plan meta dialog: rename → Save persists across reload, restore', async ({
		page
	}) => {
		// Edit-plan opens PlanMetaEditor (Modal-hosted) which exposes
		// name / days-per-week / goal-time / notes / rules. We pin the
		// rename round-trip — change Name, Save, reload, assert the
		// h1 reflects the new name, then restore. updatePlan in
		// data.ts is the write path.
		await page.goto('/plans');
		await page.getByRole('link', { name: /Sydney Half 2026/ }).click();
		await expect(page.getByRole('heading', { level: 1, name: /Sydney Half 2026/ }))
			.toBeVisible({ timeout: 10_000 });

		const restored = 'Sydney Half 2026';
		const renamed = `e2e-renamed ${Date.now()}`;

		// Open the editor.
		await page.getByRole('button', { name: /Edit plan/ }).click();
		const modal = page.locator('.modal');
		await expect(modal).toBeVisible({ timeout: 5_000 });
		// First text input in the modal is Name.
		const nameInput = modal.locator('input[type="text"]').first();
		await expect(nameInput).toHaveValue(restored);
		await nameInput.fill(renamed);
		await modal.getByRole('button', { name: 'Save', exact: true }).click();
		await expect(modal).toHaveCount(0);

		// h1 reflects the new name immediately (load() ran in onSaved).
		await expect(page.getByRole('heading', { level: 1, name: renamed }))
			.toBeVisible({ timeout: 10_000 });

		// Reload — the new value persisted server-side, not just in
		// memory.
		await page.reload();
		await expect(page.getByRole('heading', { level: 1, name: renamed }))
			.toBeVisible({ timeout: 10_000 });

		// Restore the seeded name so the rest of the suite sees it.
		await page.getByRole('button', { name: /Edit plan/ }).click();
		await expect(page.locator('.modal')).toBeVisible({ timeout: 5_000 });
		await page.locator('.modal input[type="text"]').first().fill(restored);
		await page.locator('.modal').getByRole('button', { name: 'Save', exact: true }).click();
		await expect(page.locator('.modal')).toHaveCount(0);
		await expect(page.getByRole('heading', { level: 1, name: restored }))
			.toBeVisible({ timeout: 10_000 });
	});

	test('Sydney Half plan renders multi-week grid + clicking a day opens the workout editor', async ({
		page
	}) => {
		// Drill in via the list page so we don't have to hardcode the
		// plan id — fetchActivePlan + slug-style routing means the URL
		// is /plans/<uuid>.
		await page.goto('/plans');
		await page.getByRole('link', { name: /Sydney Half 2026/ }).click();
		await expect(page).toHaveURL(/\/plans\/[0-9a-f-]+$/);

		// h1 = plan name proves the row loaded.
		await expect(
			page.getByRole('heading', { level: 1, name: /Sydney Half 2026/ })
		).toBeVisible({ timeout: 10_000 });

		// The plan generator emits multiple weeks (this plan is at
		// least 8 weeks per the seed). >=2 .week articles is the
		// load-bearing assertion — collapsing to a single week would
		// mean fetchPlanWeeks lost rows or the workoutsByWeek bucket
		// regressed.
		const weeks = page.locator('.weeks .week');
		await expect(weeks.first()).toBeVisible({ timeout: 10_000 });
		expect(await weeks.count()).toBeGreaterThanOrEqual(2);

		// Each non-rest day is a button (`.day-link`) that sets
		// `editing = wo`, mounting the WorkoutEditor inside a Modal.
		// Click the first day-link and verify a modal appears.
		await page.locator('.day-link').first().click();
		await expect(page.locator('.modal')).toBeVisible({ timeout: 5_000 });

		// Close without changes (idempotency).
		await page.locator('.modal-close').click();
		await expect(page.locator('.modal')).toHaveCount(0);
	});
});
