-- Self-audit round 3 found that deletion_audit_log.hashed_user_id
-- was set as the PRIMARY KEY in 20260917_001. A failed delete
-- attempt followed by a successful retry would conflict on PK
-- (23505), dropping the success row. The regulator-evidence trail
-- ends up with only the FAILURE recorded — exactly the case where
-- a clean audit trail matters most.
--
-- Make the table append-only: synthetic bigint identity PK, keep
-- hashed_user_id as an indexed column. Same shape otherwise; same
-- service-role-only grants. Existing rows (if any in a long-lived
-- environment) get a synthetic id assigned by the default value.

-- Drop the existing PK first so we can add the new identity column.
alter table public.deletion_audit_log
  drop constraint deletion_audit_log_pkey;

alter table public.deletion_audit_log
  add column id bigint generated by default as identity primary key;

-- Keep hashed_user_id as a non-unique index for lookups (operator
-- responding to "did you delete user X" still needs a fast query
-- path even with multiple rows per user).
create index if not exists deletion_audit_log_hashed_user_id
  on public.deletion_audit_log (hashed_user_id);

-- The hashed_user_id CHECK constraint and deleted_at index from
-- 20260917_001 stay as-is.
