-- Web-push delivery channel for the notifications inbox — the sibling of the
-- email channel (migration 20261130_001).
--
-- The notifications row (decisions §38) already drives the in-app bell and,
-- since 20261130_001, an email job per recipient. This migration adds a SECOND
-- consumer of the same rows: a `web_push` job that sends an encrypted Web Push
-- message to the recipient's subscribed browsers. The native FCM/APNs leg
-- stays deferred (operator-supplied Firebase/APNs credentials + mobile token
-- registration — docs/product/followups.md); web push needs neither. The
-- VAPID_PRIVATE_KEY is self-generated by the operator and the browser
-- subscribe path already ships (apps/web/src/lib/util/push.ts), so this leg is
-- not credential-blocked.
--
-- Four things are added:
--
--   1. notifications.web_push_sent_at — the per-channel send-state guard,
--      independent of email_sent_at. A notification can be emailed but not
--      pushed (or vice-versa) depending on each channel's separate preference
--      and whether a browser is subscribed.
--
--   2. jobs.kind += 'web_push' — the new job kind. Three-file rule
--      (apps/job_worker/CLAUDE.md): this CHECK widening + the Go dispatch case
--      (worker.go) + the pgtap test (jobs_kind_allowlist_test.sql) land
--      together.
--
--   3. clear_push_subscription(user_id, device_id) — prunes a dead browser
--      registration when the push service 404/410s it. PostgREST can't express
--      a jsonb key-delete in a PATCH, so the `prefs - 'push_subscription'`
--      minus is wrapped in a SECURITY DEFINER RPC the worker calls.
--
--   4. enqueue_notification_web_push_job() — an AFTER INSERT trigger that
--      enqueues one web_push job per notification, BUT ONLY when the recipient
--      has at least one browser push subscription. Unlike the email enqueue
--      (which fires for every row and lets the worker resolve the address),
--      web-push adoption is a minority of users; gating on subscription
--      presence here avoids manufacturing a no-op job per notification for
--      every user who never enabled browser push. A user who subscribes AFTER
--      a notification is created does not retro-receive it — same property the
--      email channel has, and the right one (notifications are ephemeral).
--
-- The notifications row stays the single source of truth: bell + email + push
-- all read the same row, each with its own *_sent_at guard and preference.

-- ─────────────────── notifications: web-push send state ───────────────────

-- NULL = not yet processed by the web-push handler; non-NULL = sent OR
-- deliberately skipped (opted out, no subscription). One column covers both
-- terminal states, mirroring email_sent_at.
alter table notifications
  add column web_push_sent_at timestamptz;

-- ─────────────────── jobs.kind allowlist += web_push ───────────────────

-- Full restate of the legal set as of 20261218_001 (safety_contacts) plus the
-- new kind. Dropping a kind here would silently break an existing enqueue
-- trigger's insert (23514 at INSERT time).
alter table public.jobs
  drop constraint jobs_kind_chk;
alter table public.jobs
  add constraint jobs_kind_chk
  check (
    kind in (
      'map_match', 'token_refresh', 'strava_event', 'photo_process',
      'notification_email', 'lifecycle_email', 'safety_email', 'web_push'
    )
  );

-- ─────────────────── prune a dead browser subscription ───────────────────

-- Called by the Go worker (kind='web_push') when the push service reports a
-- subscription is gone (404/410). Removes only the push_subscription key,
-- preserving every other per-device pref. SECURITY DEFINER so the worker's
-- service-role call can write the row regardless of RLS; the (user_id,
-- device_id) PK scopes it to exactly one registration.
create or replace function clear_push_subscription(p_user_id uuid, p_device_id text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update user_device_settings
  set prefs = prefs - 'push_subscription',
      updated_at = now()
  where user_id = p_user_id
    and device_id = p_device_id;
end;
$$;

revoke execute on function clear_push_subscription(uuid, text) from public;
grant execute on function clear_push_subscription(uuid, text) to service_role;

-- ─────────────────── enqueue trigger: notification → web_push job ───────────────────

-- One web_push job per notification, gated on the recipient having a browser
-- push subscription. The per-category preference (push_notifications) is
-- enforced in the worker — so a user on push_notifications='all' still gets
-- social pushes while the default 'important' filters them out — but the
-- coarse "do they have ANY subscription" gate lives here to avoid no-op jobs.
--
-- SECURITY DEFINER so it can read user_device_settings (RLS-scoped to the
-- owner) and write public.jobs (service_role only). Fired by the row insert,
-- never called directly, so no public/anon/authenticated grant is needed.
create or replace function enqueue_notification_web_push_job()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if exists (
    select 1 from user_device_settings d
    where d.user_id = NEW.user_id
      and d.prefs ? 'push_subscription'
  ) then
    insert into public.jobs (kind, payload)
    values (
      'web_push',
      jsonb_build_object('notification_id', NEW.id::text)
    );
  end if;
  return NEW;
end;
$$;

revoke execute on function enqueue_notification_web_push_job() from public;

create trigger notifications_enqueue_web_push
  after insert on notifications
  for each row execute function enqueue_notification_web_push_job();
