import { test } from 'node:test';
import { strict as assert } from 'node:assert';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { fold } from './catalogue_browse';

/**
 * The rail that ties the mobile twin's generated accent-fold table to THIS
 * implementation of the fold.
 *
 * `fold` reaches every canonically-decomposable letter in Unicode because the
 * runtime computes it — `normalize('NFD')`, the `Diacritic` property, the case
 * mapping. Dart's core library has none of the three, so the Dart twin reads
 * the answer from a table generated by `scripts/gen_catalogue_fold_table.mjs`.
 * Two guards keep it honest and they check different things:
 * `scripts/check_catalogue_fold_table.mjs` compares the committed table with
 * what the GENERATOR renders, which says nothing about whether the generator
 * still agrees with the function that actually ships to a browser. This does
 * that half, by running `fold` itself against the committed table.
 *
 * Deliberately one-directional. It asserts every entry in the table is what
 * `fold` answers; it does NOT sweep the whole code space asserting nothing is
 * missing, because a Node whose ICU has moved folds letters the committed table
 * predates and that failure belongs to the drift guard, which knows to say
 * "regenerate". An existing mapping changing meaning is the rare case, and it
 * is the one this catches.
 *
 * decisions § 852.
 */

const TABLE = readFileSync(
	resolve('../mobile_android/lib/catalogue_fold_table.dart'),
	'utf-8',
);

/** The body of one of the generated file's two top-level lists. */
function listBody(name: string): string {
	const open = TABLE.indexOf(`${name} = <`);
	assert.notEqual(open, -1, `the committed table has no ${name} list`);
	const start = TABLE.indexOf('[', open);
	const end = TABLE.indexOf('\n];', start);
	assert.ok(start !== -1 && end > start, `${name} is not bracketed as expected`);
	return TABLE.slice(start + 1, end);
}

/** A `const int kName = 0x...;` / `= 123;` the generated file declares. */
function constInt(name: string): number {
	const m = TABLE.match(new RegExp(`const int ${name} = (0x[0-9A-F]+|\\d+);`));
	assert.ok(m, `the committed table has no ${name} constant`);
	return Number(m[1]);
}

/** Dart's string-literal escapes, in the subset the generator emits. */
function unescapeDart(literal: string): string {
	const body = literal.slice(1, -1);
	let out = '';
	for (let i = 0; i < body.length; i++) {
		if (body[i] !== '\\') {
			out += body[i];
			continue;
		}
		i++;
		if (body[i] === 'u') {
			const close = body.indexOf('}', i);
			assert.ok(body[i + 1] === '{' && close !== -1, `unreadable escape in ${literal}`);
			out += String.fromCodePoint(Number.parseInt(body.slice(i + 2, close), 16));
			i = close;
		} else {
			out += body[i];
		}
	}
	return out;
}

const KEYS = listBody('kCatalogueFoldKeys')
	.split(',')
	.map((s) => s.trim())
	.filter(Boolean)
	.map((s) => Number.parseInt(s, 16));

const VALUES = (listBody('kCatalogueFoldValues').match(/'(?:[^'\\]|\\.)*'/g) ?? []).map(
	unescapeDart,
);

const HANGUL = {
	sBase: constInt('kHangulSyllableBase'),
	lBase: constInt('kHangulLeadBase'),
	vBase: constInt('kHangulVowelBase'),
	tBase: constInt('kHangulTrailBase'),
	tCount: constInt('kHangulTrailCount'),
	nCount: constInt('kHangulVowelTrailCount'),
	sCount: constInt('kHangulSyllableCount'),
};

/** What `catalogue_browse.dart`'s `fold` does, from the same committed data. */
function dartFold(value: string): string {
	let out = '';
	for (const ch of value) {
		const cp = ch.codePointAt(0) as number;
		const at = KEYS.indexOf(cp);
		if (at !== -1) {
			out += VALUES[at];
			continue;
		}
		const index = cp - HANGUL.sBase;
		if (index >= 0 && index < HANGUL.sCount) {
			out += String.fromCodePoint(HANGUL.lBase + Math.floor(index / HANGUL.nCount));
			out += String.fromCodePoint(
				HANGUL.vBase + Math.floor((index % HANGUL.nCount) / HANGUL.tCount),
			);
			const trail = index % HANGUL.tCount;
			if (trail !== 0) out += String.fromCodePoint(HANGUL.tBase + trail);
			continue;
		}
		out += ch;
	}
	return out;
}

test('the committed table parses into two parallel, ascending lists', () => {
	// Anti-vacuity: every assertion below is empty if this file stops being
	// readable, and a guard that inspects nothing enforces nothing.
	assert.ok(KEYS.length > 4000, `expected thousands of entries, parsed ${KEYS.length}`);
	assert.equal(KEYS.length, VALUES.length);
	for (let i = 1; i < KEYS.length; i++) {
		assert.ok(KEYS[i] > KEYS[i - 1], `key ${i} is out of order — the Dart side binary-searches`);
	}
});

test('every entry in the mobile table is what this fold answers', () => {
	const wrong: string[] = [];
	for (let i = 0; i < KEYS.length; i++) {
		const source = String.fromCodePoint(KEYS[i]);
		if (fold(source) !== VALUES[i]) {
			wrong.push(
				`U+${KEYS[i].toString(16).toUpperCase()}: table ${JSON.stringify(VALUES[i])}, ` +
					`fold ${JSON.stringify(fold(source))}`,
			);
		}
	}
	assert.deepEqual(
		wrong.slice(0, 10),
		[],
		`${wrong.length} entries disagree — re-run node scripts/gen_catalogue_fold_table.mjs`,
	);
});

test('the tabled Hangul constants are UAX #15, so the phone need not table it', () => {
	assert.equal(HANGUL.nCount, 21 * HANGUL.tCount);
	assert.equal(HANGUL.sCount, 19 * HANGUL.nCount);
	for (const cp of [0xac00, 0xbd81, 0xd55c, 0xc0b0, 0xd7a3]) {
		assert.equal(dartFold(String.fromCodePoint(cp)), fold(String.fromCodePoint(cp)));
	}
	// No syllable is in the table as well, or the two branches would disagree.
	assert.equal(
		KEYS.filter((k) => k >= HANGUL.sBase && k < HANGUL.sBase + HANGUL.sCount).length,
		0,
	);
});

test('the phone folds a real name exactly as this side does', () => {
	// The classes the hand-written table used to get wrong, plus the ones it got
	// right, run end to end through the algorithm the Dart side implements.
	const names = [
		'Đèo Hải Vân',
		'Champs-Élysées Sprint',
		'Ἀθήνα — Λυκαβηττός',
		'ΟΔΟΣ ΠΑΝΕΠΙΣΤΗΜΙΟΥ',
		'Huángshān Lǎodào',
		'Zürich, CH',
		'Ко́льский полуо́стров',
		'북한산 종주',
		'東京 5K',
		'Øst Đông Straße',
		'Ⴧ Tbilisi',
		'ǎǐǒǔ ¨¯¸·`^',
		'Central Park — Harlem Hill',
		'',
	];
	for (const name of names) {
		assert.equal(dartFold(name), fold(name), `folded differently: ${JSON.stringify(name)}`);
	}
});

test('a query the two sides fold identically finds the same names', () => {
	// The property the search rests on, checked through both implementations at
	// once: fold is applied to BOTH sides, so a match on one platform is a match
	// on the other.
	const names = ['Đèo Hải Vân', 'Ἀθήνα', 'Huángshān Lǎodào', '북한산 종주'];
	for (const query of ['hai', 'αθηνα', 'huangshan', 'shan']) {
		for (const name of names) {
			assert.equal(
				fold(name).includes(fold(query)),
				dartFold(name).includes(dartFold(query)),
				`"${query}" in "${name}" differs between the two folds`,
			);
		}
	}
});
