#!/usr/bin/env python3
"""Generate src/font.rs — the 8x16 text font for the Sharp MIP driver.

Transcribes printable ASCII (32..=126) from the pinned Spleen 8x16 BDF
vendored at `fonts/spleen-8x16.bdf` (BSD 2-Clause — see `fonts/README.md`
for the exact upstream release, its SHA256, and how to fetch it again).
Spleen is drawn pixel-by-pixel FOR 8x16 monochrome cells, which is why it
replaced the table this script used to rasterise from Source Code Pro:
thresholding a vector outline at this size leaves 1-px stems and ragged
diagonals — the '+'=='-' collision, the invisible '|', and the '!'-reads-
as-':' failure were all casualties of that pipeline (pinned from the other
side by `tests/font.rs`), and the survivors carried visibly uneven stroke
weights. A hand-designed bitmap has none of those failure modes, and the
generator becomes a pure bit transcription with NO rasteriser in the loop:
regeneration is reproducible by construction, not by pinning ImageMagick.

The numeral hero faces (`gen_bignum.py`) stay rasterised from Source Code
Pro Bold — at 32x48 and 16x32 the outline has whole pixels to land in and
the failure mode above does not exist.

Regenerate with:

    python3 scripts/gen_font.py   # from drivers/sharp_mip/

Bit convention (matches the framebuffer + the Sharp MIP wire format with
LSB-first SPI): bit 0 of each row byte is the LEFTMOST pixel, 1 = ink. BDF
bitmap rows put the leftmost pixel in the MSB, so each byte is bit-reversed
in transit.
"""

import pathlib
import re

from pinned_face import pinned_face

GLYPHS = "".join(chr(c) for c in range(32, 127))
CELL_W, CELL_H = 8, 16
BDF = pinned_face("spleen-8x16.bdf")

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parent / "src" / "font.rs"


def parse_bdf(path: pathlib.Path) -> dict[str, list[int]]:
    """Printable-ASCII glyph rows, bit 0 = leftmost, straight off the BDF.

    Every Spleen glyph is a full-cell `BBX 8 16 0 -4` bitmap, so transcription
    is row-for-row with no baseline arithmetic; that uniformity is asserted
    rather than assumed, because a glyph with a tighter bounding box would
    otherwise land shifted and the table would be wrong everywhere it is used.
    """
    glyphs: dict[str, list[int]] = {}
    encoding = None
    bbx = None
    rows: list[int] = []
    in_bitmap = False
    for line in path.read_text(encoding="ascii").splitlines():
        if line.startswith("ENCODING "):
            encoding = int(line.split()[1])
        elif line.startswith("BBX "):
            bbx = tuple(int(v) for v in line.split()[1:])
        elif line.startswith("BITMAP"):
            in_bitmap = True
            rows = []
        elif line.startswith("ENDCHAR"):
            if encoding is not None and 32 <= encoding <= 126:
                if bbx != (CELL_W, CELL_H, 0, -4):
                    raise SystemExit(
                        f"glyph {encoding} has BBX {bbx}, not the full "
                        f"{CELL_W}x{CELL_H} cell — transcription would misplace it"
                    )
                if len(rows) != CELL_H:
                    raise SystemExit(
                        f"glyph {encoding} carries {len(rows)} bitmap rows, "
                        f"expected {CELL_H}"
                    )
                glyphs[chr(encoding)] = [reverse_bits(r) for r in rows]
            in_bitmap = False
            encoding = None
            bbx = None
        elif in_bitmap:
            if not re.fullmatch(r"[0-9A-Fa-f]{2}", line.strip()):
                raise SystemExit(f"unexpected bitmap row {line!r}")
            rows.append(int(line.strip(), 16))
    return glyphs


def reverse_bits(b: int) -> int:
    return int(f"{b:08b}"[::-1], 2)


def main() -> None:
    table = parse_bdf(BDF)
    missing = [ch for ch in GLYPHS if ch not in table]
    if missing:
        raise SystemExit(f"BDF lacks printable glyphs: {missing!r}")
    glyphs = [table[ch] for ch in GLYPHS]

    # No rasteriser means no collision-repair pass, but the invariant it
    # guarded still holds the gate: two distinct printable characters that
    # pack to the same pixels are indistinguishable on the panel. Space is
    # included so an all-blank glyph trips it too.
    seen: dict[tuple[int, ...], str] = {}
    for ch, rows in zip(GLYPHS, glyphs):
        key = tuple(rows)
        if key in seen:
            raise SystemExit(
                f"glyphs {seen[key]!r} and {ch!r} are byte-identical — "
                "they would be indistinguishable on the panel"
            )
        seen[key] = ch

    emit(glyphs)


def emit(glyphs: list[list[int]]) -> None:
    lines = [
        "// Generated by scripts/gen_font.py - do not hand-edit; regenerate instead.",
        "// Glyphs transcribed from Spleen 8x16 (BSD 2-Clause).",
        "// Bit 0 of each row byte is the LEFTMOST pixel, 1 = ink.",
        "",
        "pub const GLYPH_WIDTH: usize = 8;",
        "pub const GLYPH_HEIGHT: usize = 16;",
        "pub const FIRST_CHAR: u8 = b' ';",
        "",
        "/// One entry per printable ASCII char (32..=126), 16 row bytes each.",
        f"pub const FONT: [[u8; GLYPH_HEIGHT]; {len(GLYPHS)}] = [",
    ]
    for ch, rows in zip(GLYPHS, glyphs):
        packed = ", ".join(f"0x{r:02X}" for r in rows)
        name = "space" if ch == " " else ch
        lines.append(f"    [{packed}], // {name}")
    lines.append("];")
    OUT.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"wrote {OUT} ({len(GLYPHS)} glyphs)")


if __name__ == "__main__":
    main()
