#!/usr/bin/env python3
"""Generate src/font.rs — an 8x16 bitmap font table for the Sharp MIP driver.

Rasterises printable ASCII (32..=126) from Adobe Source Code Pro (SIL OFL 1.1,
system-installed on Fedora as adobe-source-code-pro-fonts) via ImageMagick
into one 760x16 monochrome strip, then packs each 8x16 cell into the Rust
table the driver's text renderer indexes. Regenerate with:

    python3 scripts/gen_font.py   # from drivers/sharp_mip/

The output file is committed; rendering differences from an ImageMagick or
font-package upgrade show up as a reviewable diff, not a silent change.

Bit convention (matches the framebuffer + the Sharp MIP wire format with
LSB-first SPI): bit 0 of each row byte is the LEFTMOST pixel, 1 = ink.
"""

import pathlib
import subprocess
import sys
import tempfile

GLYPHS = "".join(chr(c) for c in range(32, 127))
CELL_W, CELL_H = 8, 16
# Source Code Pro's advance is 0.6 em -> a 13.333px em gives exactly 8px.
POINTSIZE = "13.3333"
FONT = "Source-Code-Pro"

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parent / "src" / "font.rs"


def render_strip(tmp: pathlib.Path) -> tuple[int, int, bytes]:
    glyph_file = tmp / "glyphs.txt"
    glyph_file.write_text(GLYPHS, encoding="ascii")
    pbm = tmp / "strip.pbm"
    subprocess.run(
        [
            "magick",
            "-background", "white",
            "-fill", "black",
            "-font", FONT,
            "-pointsize", POINTSIZE,
            "-kerning", "0",
            "+antialias",
            f"label:@{glyph_file}",
            "-depth", "1",
            str(pbm),
        ],
        check=True,
    )
    data = pbm.read_bytes()
    # P4 header: magic, whitespace, width, height, single whitespace, bits.
    if not data.startswith(b"P4"):
        raise SystemExit(f"expected raw PBM, got {data[:2]!r}")
    fields, i = [], 2
    while len(fields) < 2:
        while data[i : i + 1].isspace():
            i += 1
        if data[i : i + 1] == b"#":
            while data[i : i + 1] != b"\n":
                i += 1
            continue
        start = i
        while not data[i : i + 1].isspace():
            i += 1
        fields.append(int(data[start:i]))
    i += 1
    return fields[0], fields[1], data[i:]


def pixel(bits: bytes, width: int, x: int, y: int) -> bool:
    row_bytes = (width + 7) // 8
    byte = bits[y * row_bytes + x // 8]
    return bool(byte >> (7 - x % 8) & 1)  # PBM: MSB is leftmost, 1 = black


def main() -> None:
    with tempfile.TemporaryDirectory() as tmpdir:
        width, height, bits = render_strip(pathlib.Path(tmpdir))
    expected_w = CELL_W * len(GLYPHS)
    # label: pads a constant pixel or two on the right; per-glyph advance is
    # verified exact by the ink check below, so only under-width is fatal.
    if width < expected_w or width > expected_w + 4:
        raise SystemExit(
            f"strip is {width}px wide, expected ~{expected_w} — "
            "the font's advance no longer lands on exactly 8px; adjust POINTSIZE"
        )

    # Vertical window: the line box (ascent+descent) can exceed CELL_H. Pick
    # the 16-row window that keeps every cap top and clips only the deepest
    # descender rows — one shared window so the baseline stays aligned.
    ink_rows = [
        y
        for y in range(height)
        if any(pixel(bits, width, x, y) for x in range(expected_w))
    ]
    if not ink_rows:
        raise SystemExit("no ink in rendered strip")
    top, bottom = ink_rows[0], ink_rows[-1]
    y_off = min(top, max(0, bottom - (CELL_H - 1)))
    clipped = max(0, bottom - (y_off + CELL_H - 1))
    if clipped:
        print(f"note: clipping {clipped} descender row(s)", file=sys.stderr)

    glyphs = []
    for index in range(len(GLYPHS)):
        rows = []
        for y in range(y_off, min(height, y_off + CELL_H)):
            row = 0
            for x in range(CELL_W):
                if pixel(bits, width, index * CELL_W + x, y):
                    row |= 1 << x  # bit 0 = leftmost, per the wire format
            rows.append(row)
        rows.extend([0] * (CELL_H - len(rows)))
        glyphs.append(rows)

    lines = [
        "// Generated by scripts/gen_font.py - do not hand-edit; regenerate instead.",
        "// Glyphs rasterised from Adobe Source Code Pro (SIL OFL 1.1).",
        "// Bit 0 of each row byte is the LEFTMOST pixel, 1 = ink.",
        "",
        "pub const GLYPH_WIDTH: usize = 8;",
        "pub const GLYPH_HEIGHT: usize = 16;",
        "pub const FIRST_CHAR: u8 = b' ';",
        "",
        "/// One entry per printable ASCII char (32..=126), 16 row bytes each.",
        f"pub const FONT: [[u8; GLYPH_HEIGHT]; {len(GLYPHS)}] = [",
    ]
    for ch, rows in zip(GLYPHS, glyphs):
        packed = ", ".join(f"0x{r:02X}" for r in rows)
        name = "space" if ch == " " else ch
        lines.append(f"    [{packed}], // {name}")
    lines.append("];")
    OUT.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"wrote {OUT} ({len(GLYPHS)} glyphs)")


if __name__ == "__main__":
    main()
