#!/usr/bin/env python3
"""Generate src/bignum.rs — the 32x48 numeral face for the home clock hero.

Rasterises the clock glyph set (digits, colon, dash) from Adobe Source Code
Pro Bold (SIL OFL 1.1, the same family scripts/gen_font.py rasterises the 8x16
text font from) via ImageMagick into one monochrome strip, then packs each
32x48 cell into a Rust table. Native-resolution rasterisation is the whole
point: the old hero scaled the 8x16 text font 3x, which blew its 1-2 px
strokes up into ragged 3-6 px blocks; a real 53 px rasterisation gets the
curves and the bold stroke weight right. Regenerate with:

    python3 scripts/gen_bignum.py   # from drivers/sharp_mip/

The output file is committed; rendering differences from an ImageMagick or
font-package upgrade show up as a reviewable diff, not a silent change.

Bit convention (matches font.rs and the Sharp MIP wire format with LSB-first
SPI): bit 0 of each row byte is the LEFTMOST pixel of its 8-px span, 1 = ink.
"""

import pathlib
import subprocess
import tempfile

GLYPHS = "0123456789:-"
CELL_W, CELL_H = 32, 48
# Source Code Pro's advance is 0.6 em -> a 53.333px em gives exactly 32px.
POINTSIZE = "53.3333"
FONT = "Source-Code-Pro-Bold"

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parent / "src" / "bignum.rs"


def render_strip(tmp: pathlib.Path) -> tuple[int, int, bytes]:
    glyph_file = tmp / "glyphs.txt"
    glyph_file.write_text(GLYPHS, encoding="ascii")
    pbm = tmp / "strip.pbm"
    # Antialias + a 50% threshold: at 53px the grey coverage rounds curve
    # edges onto the pixel grid far better than a bilevel rasterisation.
    subprocess.run(
        [
            "magick",
            "-background", "white",
            "-fill", "black",
            "-font", FONT,
            "-pointsize", POINTSIZE,
            "-kerning", "0",
            "-antialias",
            f"label:@{glyph_file}",
            "-threshold", "50%",
            "-depth", "1",
            str(pbm),
        ],
        check=True,
    )
    data = pbm.read_bytes()
    if not data.startswith(b"P4"):
        raise SystemExit(f"expected raw PBM, got {data[:2]!r}")
    fields, i = [], 2
    while len(fields) < 2:
        while data[i : i + 1].isspace():
            i += 1
        if data[i : i + 1] == b"#":
            while data[i : i + 1] != b"\n":
                i += 1
            continue
        start = i
        while not data[i : i + 1].isspace():
            i += 1
        fields.append(int(data[start:i]))
    i += 1
    return fields[0], fields[1], data[i:]


def pixel(bits: bytes, width: int, x: int, y: int) -> bool:
    row_bytes = (width + 7) // 8
    byte = bits[y * row_bytes + x // 8]
    return bool(byte >> (7 - x % 8) & 1)  # PBM: MSB is leftmost, 1 = black


def main() -> None:
    with tempfile.TemporaryDirectory() as tmpdir:
        width, height, bits = render_strip(pathlib.Path(tmpdir))

    expected_w = CELL_W * len(GLYPHS)
    if width < expected_w or width > expected_w + 4:
        raise SystemExit(
            f"strip is {width}px wide, expected ~{expected_w} — "
            "the font's advance no longer lands on exactly 32px; adjust POINTSIZE"
        )

    # The clock set has no descenders, so instead of gen_font.py's baseline
    # window the whole shared ink band is centred in the 48-row cell — every
    # glyph shifts by the same offset, keeping the colon aligned to the digits.
    ink_rows = [
        y
        for y in range(height)
        if any(pixel(bits, width, x, y) for x in range(expected_w))
    ]
    if not ink_rows:
        raise SystemExit("no ink in rendered strip")
    top, bottom = ink_rows[0], ink_rows[-1]
    ink_h = bottom - top + 1
    if ink_h > CELL_H:
        raise SystemExit(f"ink is {ink_h}px tall, exceeds the {CELL_H}px cell")
    pad_top = (CELL_H - ink_h) // 2

    glyphs = []
    for index in range(len(GLYPHS)):
        rows = [[0] * (CELL_W // 8) for _ in range(CELL_H)]
        for y in range(ink_h):
            for x in range(CELL_W):
                if pixel(bits, width, index * CELL_W + x, top + y):
                    rows[pad_top + y][x // 8] |= 1 << (x % 8)
        glyphs.append(rows)

    seen = {}
    for ch, rows in zip(GLYPHS, glyphs):
        key = tuple(tuple(r) for r in rows)
        if not any(any(r) for r in rows):
            raise SystemExit(f"glyph {ch!r} rasterised blank")
        if key in seen:
            raise SystemExit(f"glyphs {seen[key]!r} and {ch!r} rasterise identically")
        seen[key] = ch

    lines = [
        "// Generated by scripts/gen_bignum.py - do not hand-edit; regenerate instead.",
        "// Glyphs rasterised from Adobe Source Code Pro Bold (SIL OFL 1.1).",
        "// Bit 0 of each row byte is the LEFTMOST pixel of its 8-px span, 1 = ink.",
        "",
        "pub const BIGNUM_WIDTH: usize = 32;",
        "pub const BIGNUM_HEIGHT: usize = 48;",
        "pub const BIGNUM_ROW_BYTES: usize = BIGNUM_WIDTH / 8;",
        "",
        "/// The clock glyph set, in table order.",
        f'pub const BIGNUM_GLYPHS: &[u8; {len(GLYPHS)}] = b"{GLYPHS}";',
        "",
        f"/// One entry per [`BIGNUM_GLYPHS`] char, {CELL_H} rows of {CELL_W // 8} bytes each.",
        f"pub const BIGNUM: [[[u8; BIGNUM_ROW_BYTES]; BIGNUM_HEIGHT]; {len(GLYPHS)}] = [",
    ]
    for ch, rows in zip(GLYPHS, glyphs):
        lines.append("    [")
        for row in rows:
            packed = ", ".join(f"0x{b:02X}" for b in row)
            lines.append(f"        [{packed}],")
        lines.append(f"    ], // {ch}")
    lines.append("];")
    OUT.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"wrote {OUT} ({len(GLYPHS)} glyphs, ink {ink_h}px tall)")


if __name__ == "__main__":
    main()
